# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 10:51
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations

from users.models import APPROVED


def set_existing_users_as_approved(apps, schema_editor):
    User = get_user_model()
    UserProfile = apps.get_model('users', 'UserProfile')
    for user in User.objects.all():
        if user.is_active:
            profile = UserProfile(user_id=user.id,
                                  assignment_status=APPROVED)
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_as_approved,
                             reverse_code=migrations.RunPython.noop)
    ]
