# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_profile_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assignment_status',
            field=models.CharField(choices=[('CREATED', 'created'), ('AWAITING_APPROVAL', 'awaiting_approval'), ('APPROVED', 'approved')], default='CREATED', max_length=30),
        ),
    ]
