version: '2'
services:

  redis:
    image: redis:4.0.9

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/.env-postgres.test

  sut:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [postgres, redis]
    links: [postgres, redis]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s -wait tcp://redis:6379 -timeout 120s
    command: ./docker/cmd-test.sh
    env_file: ./docker/.env.test
    restart: "no"
