# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_create'), ('core', '0002_auto_20180307_1748'), ('core', '0003_auto_20180423_1122'), ('core', '0004_auto_20180423_1619'), ('core', '0005_auto_20180423_1803'), ('core', '0006_auto_20180508_1331'), ('core', '0007_auto_20180809_1215'), ('core', '0008_auto_20180809_1215')]

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=1000)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historicslug',
            unique_together=set([('slug', 'page')]),
        ),
        migrations.AlterField(
            model_name='historicslug',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='historicslug',
            unique_together=set([]),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('name', 'page')]),
        ),
    ]
