# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180423_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicslug',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='historicslug',
            unique_together=set([]),
        ),
    ]
