# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 12:15
from __future__ import unicode_literals

from django.db import migrations

# This migration was not doing anything (because of Wagtail magic) and
# the code was remove. The migration is here for historic reasons


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180809_1215'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop
        )
    ]
