# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 17:46
from __future__ import unicode_literals

from directory_constants.constants import cms
from django.db import migrations


MODELS = (
    {
        'app_name': 'export_readiness',
        'class_name': 'TermsAndConditionsPage',
        'service_name': cms.EXPORT_READINESS
    },
    {
        'app_name': 'export_readiness',
        'class_name': 'PrivacyAndCookiesPage',
        'service_name': cms.EXPORT_READINESS
    },
    {
        'app_name': 'export_readiness',
        'class_name': 'GetFinancePage',
        'service_name': cms.EXPORT_READINESS
    },
    {
        'app_name': 'export_readiness',
        'class_name': 'PerformanceDashboardPage',
        'service_name': cms.EXPORT_READINESS
    },
    {
        'app_name': 'export_readiness',
        'class_name': 'PerformanceDashboardNotesPage',
        'service_name': cms.EXPORT_READINESS
    },
    {
        'app_name': 'find_a_supplier',
        'class_name': 'IndustryLandingPage',
        'service_name': cms.FIND_A_SUPPLIER
    },
    {
        'app_name': 'find_a_supplier',
        'class_name': 'IndustryArticlePage',
        'service_name': cms.FIND_A_SUPPLIER
    },
    {
        'app_name': 'find_a_supplier',
        'class_name': 'LandingPage',
        'service_name': cms.FIND_A_SUPPLIER
    },
    {
        'app_name': 'find_a_supplier',
        'class_name': 'IndustryContactPage',
        'service_name': cms.FIND_A_SUPPLIER
    },
    {
        'app_name': 'invest',
        'class_name': 'SectorLandingPage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'RegionLandingPage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'SectorPage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'SetupGuideLandingPage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'SetupGuidePage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'InvestHomePage',
        'service_name': cms.INVEST
    },
    {
        'app_name': 'invest',
        'class_name': 'InfoPage',
        'service_name': cms.INVEST
    }
)


def add_service_to_pages(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    for model in MODELS:
        model_class = apps.get_model(model['app_name'], model['class_name'])
        for page in model_class.objects.all():
            Service.objects.get_or_create(
                name=model['service_name'],
                page=page
            )


def remove_service_from_page(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.filter().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180809_1215'),
        ('export_readiness', '0010_performancedashboardnotespage'),
        ('find_a_supplier', '0061_auto_20180604_1344'),
        ('invest', '0007_auto_20180719_1414')
    ]

    operations = [
        migrations.RunPython(
            add_service_to_pages,
            reverse_code=remove_service_from_page
        )
    ]
