# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180809_1215'),
        ('export_readiness', '0010_performancedashboardnotespage'),
        ('find_a_supplier', '0061_auto_20180604_1344'),
        ('invest', '0007_auto_20180719_1414')
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        )
    ]
