# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180817_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicslug',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='historicslug',
            unique_together=set([('slug', 'service_name')]),
        ),
    ]
