# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180821_1634'),
        ('export_readiness', '0012_auto_20180821_0810'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
           reverse_code=migrations.RunPython.noop,
            elidable=True
        )
    ]


