# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180821_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='service',
            name='page',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
