# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 14:56
from __future__ import unicode_literals

from directory_constants import cms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180822_0915'),
        ('export_readiness', '0013_exportreadinessapp_service_name'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        )
    ]
