# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 15:45
from __future__ import unicode_literals

from django.db import migrations


apps_model_pairs_untranslated = (
    ('export_readiness', 'GetFinancePage'),
)


def populate_untranslated_breadcrumbs(apps, schema_editor):
    Breadcrumb = apps.get_model('core', 'Breadcrumb')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for app_name, model_name in apps_model_pairs_untranslated:
        historic_model = apps.get_model(app_name, model_name)
        for page in historic_model.objects.all():
            content_type = ContentType.objects.get_for_model(page)
            Breadcrumb.objects.create(
                service_name=page.service_name,
                slug=page.slug,
                object_id=page.pk,
                content_type=content_type,
                label=page.breadcrumbs_label,
            )


def delete_breadcrumbs(apps, schema_editor):
    Breadcrumb = apps.get_model('core', 'Breadcrumb')
    Breadcrumb.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180823_2014'),
    ]

    operations = [
        migrations.RunPython(
            populate_untranslated_breadcrumbs,
            delete_breadcrumbs,
            elidable=True
        )
    ]
