# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180824_1622'),
        ('core', '0018_merge_20180829_0828'),
    ]

    operations = [
    ]
