# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 06:32
from __future__ import unicode_literals

from django.db import migrations


def populate_historic_slug_service_name(apps, schema_editor):
    HistoricSlug = apps.get_model('core', 'HistoricSlug')
    for historic_slug in HistoricSlug.objects.all():
        content_type = historic_slug.page.content_type
        page_class = apps.get_model(content_type.app_label, content_type.model)
        page = page_class.objects.get(pk=historic_slug.page_id)
        historic_slug.service_name = page.service_name
        historic_slug.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20180829_0939'),
    ]

    operations = [
        migrations.RunPython(
           populate_historic_slug_service_name,
           reverse_code=migrations.RunPython.noop
        )
    ]
