# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180830_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicslug',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='historicslug',
            name='page',
        ),
        migrations.DeleteModel(
            name='HistoricSlug',
        ),
    ]
