# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 07:58
from __future__ import unicode_literals

from django.db import migrations

def populate_slug(apps, schema_migrations):
    ExportReadinessApp = apps.get_model(
        'export_readiness', 'ExportReadinessApp'
    )
    ExportReadinessApp.objects.all().update(slug='export-readiness-app')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180906_1344'),
        ('export_readiness', '0019_auto_20180905_1350'),
    ]

    operations = [
       migrations.RunPython(
           populate_slug,
           reverse_code=migrations.RunPython.noop,
           elidable=True
        )
    ]
