# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0024_auto_20180913_1321'), ('core', '0025_documenthash')]

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('core', '0023_auto_20180912_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='DocumentHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=1000)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
