# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_documenthash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumb',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components')], db_index=True, max_length=50, null=True),
        ),
    ]
