# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0027_auto_20190206_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path_prefix', models.CharField(blank=True, help_text="When determining URLs for a page in this site, the page's 'url_path' is prepended with this value to create a URL that will be recognised by the relevant front-end app.", max_length=100)),
                ('include_port_in_urls', models.BooleanField(default=True, help_text="This allows us to add dummy port values to Wagtail Site objects, to get around the unique hostname/port restrictions. If unchecked, the port won't be included in page URLs, and so becomes inconsequential.", verbose_name='include port in page URLs')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
