# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_routingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_pt_br',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_ru',
        ),
    ]
