# Generated by Django 2.2.24 on 2021-10-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('core', '0029_auto_20190417_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatMedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailmedia.Media')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcript')),
                ('subtitles_en', models.TextField(blank=True, help_text='English-language subtitles for this video, in VTT format', null=True, verbose_name='English subtitles')),
            ],
            options={
                'verbose_name': 'media',
                'abstract': False,
            },
            bases=('wagtailmedia.media',),
        ),
    ]
