# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 10:04
from __future__ import unicode_literals

import core.model_fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    replaces = [('great_international', '0001_initial'), ('great_international', '0002_auto_20190206_1146'), ('great_international', '0003_internationalarticlelistingpage'), ('great_international', '0003_auto_20190211_1202'), ('great_international', '0004_merge_20190212_1003'), ('great_international', '0005_internationalukhqpages'), ('great_international', '0006_internationaltopiclandingpage'), ('great_international', '0007_auto_20190219_1114'), ('great_international', '0008_auto_20190222_1554'), ('great_international', '0008_auto_20190222_1230'), ('great_international', '0009_merge_20190225_1214'), ('great_international', '0010_auto_20190228_0819'), ('great_international', '0011_auto_20190228_1051'), ('great_international', '0012_internationalsectorpage'), ('great_international', '0013_auto_20190301_1227'), ('great_international', '0014_auto_20190304_1215'), ('great_international', '0015_auto_20190306_1521')]

    initial = True

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('export_readiness', '0049_auto_20190207_0924'),
        ('wagtailimages', '0021_image_file_hash'),
        ('export_readiness', '0047_allcontactpagespage'),
        ('wagtailcore', '0040_page_draft_title'),
        ('export_readiness', '0050_auto_20190219_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatInternationalApp',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='InternationalArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('article_title', models.CharField(max_length=255)),
                ('article_teaser', models.CharField(max_length=255)),
                ('article_body_text', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('article_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('related_page_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
                ('related_page_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
                ('related_page_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InternationalHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('tariffs_title', models.CharField(max_length=255)),
                ('tariffs_description', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('tariffs_link', models.URLField()),
                ('news_title', models.CharField(max_length=255)),
                ('tariffs_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='InternationalCampaignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('campaign_heading', models.CharField(max_length=255)),
                ('section_one_heading', models.CharField(max_length=255)),
                ('section_one_intro', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('selling_point_one_heading', models.CharField(max_length=255)),
                ('selling_point_one_content', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('selling_point_two_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_two_content', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('selling_point_three_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_three_content', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('section_one_contact_button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_one_contact_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section_two_heading', models.CharField(max_length=255)),
                ('section_two_intro', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('section_two_contact_button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_two_contact_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('related_content_heading', models.CharField(max_length=255)),
                ('related_content_intro', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('cta_box_message', models.CharField(max_length=255)),
                ('cta_box_button_url', models.CharField(max_length=255)),
                ('cta_box_button_text', models.CharField(max_length=255)),
                ('campaign_hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('related_page_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
                ('related_page_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
                ('related_page_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage')),
                ('section_one_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('section_two_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('selling_point_one_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('selling_point_three_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('selling_point_two_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InternationalArticleListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('landing_page_title', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('list_teaser', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InternationalTopicLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('landing_page_title', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InternationalRegionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='internationalarticlelistingpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationalcampaignpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationaltopiclandingpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.CreateModel(
            name='InternationalLocalisedFolderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='internationalcampaignpage',
            name='campaign_teaser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.CreateModel(
            name='InternationalSectorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('heading_teaser', models.TextField(blank=True)),
                ('section_one_body', core.model_fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Bullets markdown')),
                ('statistic_1_number', models.CharField(max_length=255)),
                ('statistic_1_heading', models.CharField(max_length=255)),
                ('statistic_1_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_2_number', models.CharField(max_length=255)),
                ('statistic_2_heading', models.CharField(max_length=255)),
                ('statistic_2_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_3_number', models.CharField(blank=True, max_length=255)),
                ('statistic_3_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_3_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_4_number', models.CharField(blank=True, max_length=255)),
                ('statistic_4_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_4_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_5_number', models.CharField(blank=True, max_length=255)),
                ('statistic_5_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_5_smallprint', models.CharField(blank=True, max_length=255)),
                ('statistic_6_number', models.CharField(blank=True, max_length=255)),
                ('statistic_6_heading', models.CharField(blank=True, max_length=255)),
                ('statistic_6_smallprint', models.CharField(blank=True, max_length=255)),
                ('section_two_heading', models.CharField(max_length=255, verbose_name='Highlights heading')),
                ('section_two_teaser', models.TextField(verbose_name='Highlights teaser')),
                ('section_two_subsection_one_heading', models.CharField(max_length=255, verbose_name='Highlight 1 heading')),
                ('section_two_subsection_one_body', models.TextField(verbose_name='Highlight 1 body')),
                ('section_two_subsection_two_heading', models.CharField(max_length=255, verbose_name='Highlight 2 heading')),
                ('section_two_subsection_two_body', models.TextField(verbose_name='Highlight 2 body')),
                ('section_two_subsection_three_heading', models.CharField(max_length=255, verbose_name='Highlight 3 heading')),
                ('section_two_subsection_three_body', models.TextField(verbose_name='Highlight 3 body')),
                ('case_study_title', models.CharField(blank=True, max_length=255)),
                ('case_study_description', models.CharField(blank=True, max_length=255)),
                ('case_study_cta_text', models.TextField(blank=True)),
                ('section_three_heading', models.CharField(blank=True, max_length=255, verbose_name='Fact sheets heading')),
                ('section_three_teaser', models.TextField(blank=True, verbose_name='Fact sheets teaser')),
                ('section_three_subsection_one_heading', models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 1 heading')),
                ('section_three_subsection_one_teaser', models.TextField(blank=True, verbose_name='Fact sheet 1 teaser')),
                ('section_three_subsection_one_body', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Fact sheet 1 body')),
                ('section_three_subsection_two_heading', models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 2 heading')),
                ('section_three_subsection_two_teaser', models.TextField(blank=True, verbose_name='Fact sheet 2 teaser')),
                ('section_three_subsection_two_body', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Fact sheet 2 body')),
                ('case_study_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('related_page_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('related_page_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('related_page_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('section_one_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bullets image')),
                ('section_two_subsection_one_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 1 icon')),
                ('section_two_subsection_three_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 3 icon')),
                ('section_two_subsection_two_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 2 icon')),
                ('case_study_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag')),
                ('section_one_image_caption', models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption')),
                ('section_one_image_caption_company', models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption — company name')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
