# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0002_auto_20190206_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalcampaignpage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage'),
        ),
        migrations.AlterField(
            model_name='internationalcampaignpage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage'),
        ),
        migrations.AlterField(
            model_name='internationalcampaignpage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalArticlePage'),
        ),
    ]
