# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0003_internationalarticlelistingpage'),
        ('great_international', '0003_auto_20190211_1202'),
    ]

    operations = [
    ]
