# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 16:26
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0003_auto_20190313_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalGuideLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('display_title', models.CharField(max_length=255)),
                ('teaser', models.CharField(max_length=255)),
                ('section_one_content', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks], verbose_name='content')),
                ('section_one_image_caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption')),
                ('section_two_heading', models.CharField(max_length=100, verbose_name='heading')),
                ('section_two_teaser', models.TextField(verbose_name='teaser')),
                ('section_two_button_text', models.CharField(max_length=100, verbose_name='button text')),
                ('section_two_button_url', models.CharField(max_length=255, verbose_name='button URL')),
                ('guides_section_heading', models.CharField(max_length=100, verbose_name='section heading')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('section_one_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image')),
                ('section_two_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
