# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 17:50
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0004_internationalguidelandingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Case study link URL'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_cta_text',
            field=models.TextField(blank=True, verbose_name='Case study link text'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Sector name'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='heading_teaser',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body',
            field=core.model_fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image caption'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_caption_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image caption attribution'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading',
            field=models.CharField(max_length=255, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body',
            field=models.TextField(verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading',
            field=models.CharField(max_length=255, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Spotlight 1 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body',
            field=models.TextField(verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading',
            field=models.CharField(max_length=255, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Spotlight 3 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body',
            field=models.TextField(verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading',
            field=models.CharField(max_length=255, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Spotlight 2 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser',
            field=models.TextField(verbose_name='Spotlight summary'),
        ),
    ]
