# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 09:45
from __future__ import unicode_literals

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0005_auto_20190320_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalarticlepage',
            name='article_subheading',
            field=models.CharField(blank=True, help_text='This is a subheading that displays when the article is featured on another page', max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcampaignpage',
            name='campaign_subheading',
            field=models.CharField(blank=True, help_text='This is a subheading that displays when the article is featured on another page', max_length=255),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_title',
            field=models.CharField(default='We are Open.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_content',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_title',
            field=models.CharField(default='Invest in the UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='study_in_uk_cta_text',
            field=models.CharField(default='Study in the UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='tariffs_call_to_action_text',
            field=models.CharField(default='Continue', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_content',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_title',
            field=models.CharField(default='Trade with the UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='visit_uk_cta_text',
            field=models.CharField(default='Visit the UK', max_length=255),
            preserve_default=False,
        ),
    ]
