# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 12:24
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0005_auto_20190320_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='hero_title',
            field=models.CharField(default='International', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_title',
            field=models.CharField(default='Invest', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='tariffs_call_to_action_text',
            field=models.CharField(default='CTA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='trade_title',
            field=models.CharField(default='Trade', max_length=255),
            preserve_default=False,
        ),
    ]
