# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 16:42
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0005_internationalhomepage_tariffs_call_to_action_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_content_left',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_content_right',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_title_left',
            field=models.CharField(default='Invest with the UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_title_right',
            field=models.CharField(default='Trade with the UK', max_length=255),
            preserve_default=False,
        ),
    ]
