# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0006_auto_20190319_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_image_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='invest_trade_section_image_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
