# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 10:37
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0049_auto_20190207_0924'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('great_international', '0006_internationaltopiclandingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalRegionPages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='internationalukhqpages',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='internationalarticlelistingpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationalcampaignpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationalmarketingpages',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AddField(
            model_name='internationaltopiclandingpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.DeleteModel(
            name='InternationalUKHQPages',
        ),
    ]
