# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0007_auto_20190221_1758'),
        ('great_international', '0007_auto_20190219_1114'),
    ]

    operations = [
    ]
