# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 12:31
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0007_internationalcapitalinvestlandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text',
            field=models.CharField(default='Get in touch', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title',
            field=models.CharField(default='Contact our investment team', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text',
            field=models.CharField(default='UK Energy brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title',
            field=models.CharField(default='UK Energy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text',
            field=models.CharField(default='Contact our investment team', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text',
            field=models.CharField(default='Help international investors navigate their investment journey', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text',
            field=models.CharField(default='Give guidance on UK regulations and policy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text',
            field=models.CharField(default='Align international investors with credible projects pipeline', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title',
            field=models.CharField(default='How we help', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text',
            field=models.CharField(default='Work with UK organisations to ensure their offer is investable', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title',
            field=models.CharField(default='Why choose the UK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_cta_text',
            field=models.CharField(default='Northern Ireland brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_title',
            field=models.CharField(default='Northern Ireland', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_cta_text',
            field=models.CharField(default='Midlands brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_title',
            field=models.CharField(default='Midlands Engine', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_cta_text',
            field=models.CharField(default='South England brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_title',
            field=models.CharField(default='South England', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_cta_text',
            field=models.CharField(default='Wales brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_title',
            field=models.CharField(default='Wales', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_cta_text',
            field=models.CharField(default='Midlands brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_title',
            field=models.CharField(default='Midlands Engine', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_cta_text',
            field=models.CharField(default='Powerhouse brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_title',
            field=models.CharField(default='Northern Powerhouse', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title',
            field=models.CharField(default='Large scale capital projects', max_length=255),
            preserve_default=False,
        ),
    ]
