# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0008_auto_20190222_1230'),
        ('great_international', '0008_auto_20190222_1554'),
    ]

    operations = [
    ]
