# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0009_merge_20190225_1214'),
        ('great_international', '0008_auto_20190227_1405'),
    ]

    operations = [
    ]
