# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 16:09
from __future__ import unicode_literals

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0012_internationalsectorpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalsectorpage',
            name='case_study_cta_url',
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='case_study_cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='heading_teaser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Bullets markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bullets image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheets heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_one_body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Fact sheet 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_one_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_one_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 1 teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_two_body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Fact sheet 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_two_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheet 2 teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fact sheets teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading',
            field=models.CharField(max_length=255, verbose_name='Highlights heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body',
            field=models.CharField(max_length=255, verbose_name='Highlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading',
            field=models.CharField(max_length=255, verbose_name='Highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 1 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body',
            field=models.CharField(max_length=255, verbose_name='Highlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading',
            field=models.CharField(max_length=255, verbose_name='Highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 3 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body',
            field=models.CharField(max_length=255, verbose_name='Highlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading',
            field=models.CharField(max_length=255, verbose_name='Highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Highlight 2 icon'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser',
            field=models.CharField(max_length=255, verbose_name='Highlights teaser'),
        ),
    ]
