# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 13:21
from __future__ import unicode_literals

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0012_auto_20190404_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='display_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_heading_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_ar',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_de',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_en_gb',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_es',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_fr',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_ja',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_pt',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_pt_br',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_ru',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_five_url_zh_hans',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_heading_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_ar',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_de',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_en_gb',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_es',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_fr',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_ja',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_pt',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_pt_br',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_ru',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_four_url_zh_hans',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_content_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_heading_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_section_heading_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_heading_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_ar',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_de',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_en_gb',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_es',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_fr',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_ja',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_pt',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_pt_br',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_ru',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_three_url_zh_hans',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_content_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_heading_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='feature_two_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalcuratedtopiclandingpage',
            name='teaser_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
