# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0013_auto_20190301_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalsectorpage',
            name='next_steps_description',
        ),
        migrations.RemoveField(
            model_name='internationalsectorpage',
            name='next_steps_heading',
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='section_one_image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption'),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='section_one_image_caption_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption — company name'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='heading_teaser',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_one_teaser',
            field=models.TextField(blank=True, verbose_name='Fact sheet 1 teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_subsection_two_teaser',
            field=models.TextField(blank=True, verbose_name='Fact sheet 2 teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_three_teaser',
            field=models.TextField(blank=True, verbose_name='Fact sheets teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body',
            field=models.TextField(verbose_name='Highlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body',
            field=models.TextField(verbose_name='Highlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body',
            field=models.TextField(verbose_name='Highlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser',
            field=models.TextField(verbose_name='Highlights teaser'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
