# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 13:22
from __future__ import unicode_literals

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0013_auto_20190404_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='display_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_de',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_es',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='guides_section_heading_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='section heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_content_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='content'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_pt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_pt_br',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_caption_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image caption'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_pt_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_one_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_de',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_es',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_text_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_de',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_es',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_button_url_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='button URL'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_de',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_es',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_heading_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_pt_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_ar',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_de',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_en_gb',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_es',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_fr',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_ja',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_pt',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_pt_br',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_ru',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='section_two_teaser_zh_hans',
            field=models.TextField(null=True, verbose_name='teaser'),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalguidelandingpage',
            name='teaser_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
