# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('great_international', '0014_auto_20190329_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
