# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0014_auto_20190404_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_pt_br',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='case_study_description_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
