# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0007_internationalhomepage_hero_cta_link'),
        ('great_international', '0016_auto_20190408_1640'),
    ]

    operations = [
    ]
