# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0018_auto_20190401_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_ar',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_de',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_en_gb',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_es',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_fr',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_ja',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_pt',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_pt_br',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_ru',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_subheading_zh_hans',
            field=models.CharField(blank=True, help_text="Please use if you'd like to add to the title on a second line", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
