# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0019_internationalcapitalinvestlandingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestRegionOpportunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_title_en_gb', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_zh_hans', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_pt_br', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_ar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
