# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0020_auto_20190417_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_heading_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_heading_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_three_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_heading_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_link_two_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_summary_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='featured_links_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight title'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 5 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 5 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 4 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 4 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 1 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 1 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 6 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 6 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 3 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 3 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body',
            field=models.TextField(blank=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight 2 body'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_icon_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Features highlight 2 icon'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser',
            field=models.TextField(blank=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_de',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_es',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='section_two_teaser_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Features highlight summary'),
        ),
    ]
