# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 12:19
from __future__ import unicode_literals

import wagtailmarkdown.fields
import core.models
import core.validators
import core.wagtail_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0022_auto_20190508_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalEUExitFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('uses_tree_based_routing', models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled')),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('body_text', wagtailmarkdown.fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('submit_button_text', models.CharField(max_length=50)),
                ('disclaimer', models.TextField(max_length=500)),
                ('first_name_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('first_name_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('last_name_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('last_name_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('email_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('email_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('organisation_type_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('organisation_type_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('company_name_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('company_name_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('country_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('country_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('city_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('city_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('comment_help_text', core.wagtail_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('comment_label', core.wagtail_fields.FormLabelField(max_length=200, verbose_name='label')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='InternationalEUExitFormSuccessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('uses_tree_based_routing', models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled')),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255, verbose_name='Title')),
                ('body_text', models.CharField(max_length=255, verbose_name='Body text')),
                ('next_title', models.CharField(max_length=255, verbose_name='Title')),
                ('next_body_text', models.CharField(max_length=255, verbose_name='Body text')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
