# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 16:41
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0023_capitalinvestopportunitylistingpage_capitalinvestopportunitypage_capitalinvestregionalsectoropportun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumbs_label', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
                ('opportunity_summary_intro', models.TextField(max_length=255)),
                ('opportunity_summary_content', core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks])),
                ('location', models.CharField(max_length=255)),
                ('project_promoter', models.CharField(max_length=255)),
                ('scale', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('investment_type', models.CharField(max_length=255)),
                ('planning_status', models.CharField(max_length=255)),
                ('project_background_title', models.CharField(blank=True, max_length=255)),
                ('project_background_intro', models.TextField(blank=True, max_length=255)),
                ('project_description_title', models.CharField(blank=True, max_length=255)),
                ('project_description_content', core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks])),
                ('project_promoter_title', models.CharField(blank=True, max_length=255)),
                ('project_promoter_content', core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks])),
                ('case_study_title', models.CharField(max_length=255)),
                ('case_study_text', models.CharField(blank=True, max_length=255)),
                ('case_study_cta_text', models.CharField(max_length=255)),
                ('case_study_cta_link', models.CharField(blank=True, max_length=255)),
                ('next_steps_title', models.CharField(max_length=255)),
                ('next_steps_intro', models.CharField(blank=True, max_length=255)),
                ('invest_cta_text', models.CharField(max_length=255)),
                ('buy_cta_text', models.CharField(max_length=255)),
                ('case_study_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('opportunity_summary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('project_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.AddField(
            model_name='capitalinvestregionalsectoropportunitypage',
            name='opportunities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='great_international.Opportunity'),
        ),
    ]
