# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0024_auto_20190509_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opportunity',
            new_name='OpportunitySnippet',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_one_zh_hans',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_three_zh_hans',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestregionalsectorpage',
            name='related_page_two_zh_hans',
        ),
    ]
