# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 16:49
from __future__ import unicode_literals

from django.db import migrations


def unset_page_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')
    page_ct = ContentType.objects.get(app_label='wagtailcore', model='page')
    homepage_ct = ContentType.objects.get(app_label='great_international', model='internationalhomepage')
    Page.objects.filter(content_type=homepage_ct).update(content_type=page_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0025_populate_apppage_fields_from_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalHomePage',
        ),
        migrations.RunPython(
            unset_page_content_type, migrations.RunPython.noop
        ),
    ]
