# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 08:37
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0025_auto_20190523_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_five_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_four_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_one_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_six_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_three_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_card_two_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
