# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0026_capitalinvestopportunitylistingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1',
            new_name='related_page_one',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_ar',
            new_name='related_page_one_ar',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_de',
            new_name='related_page_one_de',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_en_gb',
            new_name='related_page_one_en_gb',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_es',
            new_name='related_page_one_es',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_fr',
            new_name='related_page_one_fr',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_ja',
            new_name='related_page_one_ja',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_pt',
            new_name='related_page_one_pt',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_pt_br',
            new_name='related_page_one_pt_br',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_ru',
            new_name='related_page_one_ru',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_1_zh_hans',
            new_name='related_page_one_zh_hans',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2',
            new_name='related_page_three',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_ar',
            new_name='related_page_three_ar',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_de',
            new_name='related_page_three_de',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_en_gb',
            new_name='related_page_three_en_gb',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_es',
            new_name='related_page_three_es',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_fr',
            new_name='related_page_three_fr',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_ja',
            new_name='related_page_three_ja',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_pt',
            new_name='related_page_three_pt',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_pt_br',
            new_name='related_page_three_pt_br',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_ru',
            new_name='related_page_three_ru',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_2_zh_hans',
            new_name='related_page_three_zh_hans',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3',
            new_name='related_page_two',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_ar',
            new_name='related_page_two_ar',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_de',
            new_name='related_page_two_de',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_en_gb',
            new_name='related_page_two_en_gb',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_es',
            new_name='related_page_two_es',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_fr',
            new_name='related_page_two_fr',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_ja',
            new_name='related_page_two_ja',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_pt',
            new_name='related_page_two_pt',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_pt_br',
            new_name='related_page_two_pt_br',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_ru',
            new_name='related_page_two_ru',
        ),
        migrations.RenameField(
            model_name='capitalinvestsectorpage',
            old_name='related_page_3_zh_hans',
            new_name='related_page_two_zh_hans',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_pt_br',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_ru',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_4_zh_hans',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_pt_br',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_ru',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_5_zh_hans',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_ar',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_de',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_en_gb',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_es',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_fr',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_ja',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_pt',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_pt_br',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_ru',
        ),
        migrations.RemoveField(
            model_name='capitalinvestsectorpage',
            name='related_page_6_zh_hans',
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_one_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_three_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_page_two_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_one_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_three_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='related_page_two_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
