# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 08:40
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0026_auto_20190524_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='featured_description_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
