# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0028_auto_20190517_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='buy_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='case_study_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='invest_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='location_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='next_steps_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='opportunity_summary_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='programme_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='similar_projects_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='buy_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='invest_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='investment_opportunities_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionalsectorpage',
            name='next_steps_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='buy_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='case_study_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='invest_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='investment_opps_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment opportunities title'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='next_steps_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='region_summary_section_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='contact_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='energy_sector_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='hero_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_four_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_one_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_three_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='how_we_help_two_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='reason_to_invest_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
        migrations.AlterField(
            model_name='internationalcapitalinvestlandingpage',
            name='region_ops_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region opportunities section title'),
        ),
    ]
