# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0030_auto_20190524_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapitalInvestRegionCardField',
            new_name='CapitalInvestRegionCardFieldsSummary',
        ),
    ]
