# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('wagtailimages', '0021_image_file_hash'),
        ('great_international', '0031_auto_20190524_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestHomesInEnglandCardFieldsSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('homes_in_england_card_title', models.CharField(blank=True, max_length=255)),
                ('homes_in_england_card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('homes_in_england_card_pdf_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_ar',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_de',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_en_gb',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_es',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_fr',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_ja',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_pt',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_content_zh_hans',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_ar',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_de',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_en_gb',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_es',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_fr',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_ja',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_pt',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_cta_text_zh_hans',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_ar',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_de',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_es',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_fr',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_ja',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_pt',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_ar',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_de',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_en_gb',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_es',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_fr',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_ja',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_pt',
        ),
        migrations.RemoveField(
            model_name='internationalcapitalinvestlandingpage',
            name='homes_in_england_section_pdf_document_zh_hans',
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_ar',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_de',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_en_gb',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_es',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_fr',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_ja',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_pt',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
        migrations.AddField(
            model_name='capitalinvesthomesinenglandcardfieldssummary',
            name='page_zh_hans',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_homes_in_england_card_fields', to='great_international.InternationalCapitalInvestLandingPage'),
        ),
    ]
