# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0031_auto_20190606_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestRelatedSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_ar', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_de', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_en_gb', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_es', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_fr', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_ja', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_pt', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
                ('page_zh_hans', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sectors', to='great_international.CapitalInvestOpportunityPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='prioritised_opportunity',
            field=models.BooleanField(default=False, help_text='Prioritise project?'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsectors',
            name='related_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.InternationalSectorPage'),
        ),
    ]
