# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0032_auto_20190606_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalsectorpage',
            name='prioritised_opportunity',
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='prioritised_opportunity',
            field=models.BooleanField(default=False, help_text='Prioritise project?'),
        ),
    ]
