# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0032_remove_internationalhomepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreatInternationalApp',
            new_name='InternationalHomePage',
        ),
    ]
