# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0033_auto_20190606_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='prioritised_opportunity',
            field=models.BooleanField(default=False, verbose_name='Prioritise project?'),
        ),
    ]
