# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0035_auto_20190606_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestopportunitypage',
            name='scale_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='capitalinvestregionpage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body',
            field=models.TextField(blank=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 1 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_one_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body',
            field=models.TextField(blank=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 3 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_three_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body',
            field=models.TextField(blank=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_de',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_body_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight 2 body'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_subsection_two_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser',
            field=models.TextField(blank=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_de',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_es',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_two_teaser_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Spotlight summary'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_1_number_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_heading_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='statistic_2_number_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
