# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:20
from __future__ import unicode_literals

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    internationalhompepage_ct = ContentType.objects.filter(model='internationalhomepage').first()
    greatinternationalapp_ct = ContentType.objects.filter(model='greatinternationalapp').first()
    internationalhompepageold_ct, _ = ContentType.objects.get_or_create(
        app_label='great_international', model='internationalhomepageold'
    )

    if internationalhompepage_ct and greatinternationalapp_ct:
        Page.objects.filter(content_type=internationalhompepage_ct).update(content_type=internationalhompepageold_ct)
        Page.objects.filter(content_type=greatinternationalapp_ct).update(content_type=internationalhompepage_ct)


def migrate_backwards(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    internationalhompepage_ct = ContentType.objects.filter(model='internationalhomepage').first()

    if internationalhompepage_ct:
        greatinternationalapp_ct, _ = ContentType.objects.get_or_create(
            app_label='great_international', model='greatinternationalapp')
        internationalhompepageold_ct, _ = ContentType.objects.get_or_create(
            app_label='great_international', model='internationalhomepageold')
        Page.objects.filter(content_type=internationalhompepage_ct).update(content_type=greatinternationalapp_ct)
        Page.objects.filter(content_type=internationalhompepageold_ct).update(content_type=internationalhompepage_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0036_rename_greatinternationalapp_to_internationalhomepage'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards),
    ]
