# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:20
from __future__ import unicode_literals

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    internationalhompepage_ct, _ = ContentType.objects.get_or_create(
        app_label='great_international', model='internationalhomepage')
    internationalhompepageold_ct, _ = ContentType.objects.get_or_create(
        app_label='great_international', model='internationalhomepageold')

    Page.objects.filter(url_path='/great-international-app/').update(content_type=internationalhompepage_ct)
    Page.objects.filter(url_path='/great-international-app/international/').update(content_type=internationalhompepageold_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('great_international', '0036_rename_greatinternationalapp_to_internationalhomepage'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
