# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0033_auto_20190611_1057'),
        ('great_international', '0037_correct_page_contenttypes'),
    ]

    operations = [
    ]
