# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 11:33
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0037_auto_20190607_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_body_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='section_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
    ]
