# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0039_auto_20190612_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading',
            field=models.CharField(blank=True, default='Investment type', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_ar',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_de',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_en_gb',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_es',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_fr',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_ja',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_pt',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='investment_type_heading_zh_hans',
            field=models.CharField(blank=True, default='Investment type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading',
            field=models.CharField(blank=True, default='Location', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_ar',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_de',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_en_gb',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_es',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_fr',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_ja',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_pt',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='location_heading_zh_hans',
            field=models.CharField(blank=True, default='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading',
            field=models.CharField(blank=True, default='Planning status', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_ar',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_de',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_en_gb',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_es',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_fr',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_ja',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_pt',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='planning_status_heading_zh_hans',
            field=models.CharField(blank=True, default='Planning status', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading',
            field=models.CharField(blank=True, default='Project promoter', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_ar',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_de',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_en_gb',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_es',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_fr',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_ja',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_pt',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='project_promoter_heading_zh_hans',
            field=models.CharField(blank=True, default='Project promoter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading',
            field=models.CharField(blank=True, default='Scale', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_ar',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_de',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_en_gb',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_es',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_fr',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_ja',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_pt',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_heading_zh_hans',
            field=models.CharField(blank=True, default='Scale', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading',
            field=models.CharField(blank=True, default='Sector', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_ar',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_de',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_en_gb',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_es',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_fr',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_ja',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_pt',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='sector_heading_zh_hans',
            field=models.CharField(blank=True, default='Sector', max_length=255, null=True),
        ),
    ]
