# Generated by Django 2.2.2 on 2019-07-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0044_update_homepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='related_region_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.CapitalInvestRegionPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_ar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_de',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_en_gb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_es',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_fr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_ja',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_pt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
        migrations.AddField(
            model_name='capitalinvestopportunitypage',
            name='scale_value_zh_hans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Scale value (in millions)'),
        ),
    ]
