# Generated by Django 2.2.2 on 2019-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0045_auto_20190701_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalsectorpage',
            name='related_opportunities_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
