# Generated by Django 2.2.2 on 2019-07-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0046_auto_20190702_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalinvestopportunitypage',
            name='prioritised_opportunity',
        ),
    ]
