# Generated by Django 2.2.2 on 2019-07-17 15:37

import core.model_fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import great_international.panels.invest


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('great_international', '0047_investregionlandingpage_investsectorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestHighPotentialOpportunitiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('uses_tree_based_routing', models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page', great_international.panels.invest.InvestHighPotentialOpportunitiesPagePanels),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_eight_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_five_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_four_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_one_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_seven_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_six_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_three_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_en_gb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_ja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='companies_list_item_image_two_alt_text_zh_hans',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_ar',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_de',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_es',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_fr',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_ja',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_pt',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='opportunity_list_image_alt_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_ar',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_de',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_es',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_fr',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_ja',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_pt',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_image_alt_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_one_video_transcript_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_ar',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_de',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_es',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_fr',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_ja',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_pt',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_image_alt_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, help_text='This image alt text can be multi-paragraph or contain tables if the image shows complex data such as a chart.', null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhighpotentialopportunitydetailpage',
            name='proposition_two_video_transcript_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
