# Generated by Django 2.2.2 on 2019-07-11 12:03

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0048_auto_20190711_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_ar',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_de',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_en_gb',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_es',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_fr',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_ja',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_pt',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
        migrations.AddField(
            model_name='capitalinvestrelatedsubsectors',
            name='page_zh_hans',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sub_sectors', to='great_international.CapitalInvestOpportunityPage'),
        ),
    ]
