# Generated by Django 2.2.2 on 2019-07-22 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0001_squashed_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('great_international', '0050_investhighpotentialopportunitiespage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestSectorPage',
            new_name='InvestRegionPage',
        ),
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='how_we_help_icon_six',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_five_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_four_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_one_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_seven_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_six_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_three_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_content_two_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_five_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_four_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_one_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_seven_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_six_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_three_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_ar',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_de',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_en_gb',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_es',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_fr',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_ja',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_pt',
        ),
        migrations.RemoveField(
            model_name='investinternationalhomepage',
            name='subsection_title_two_zh_hans',
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title',
            field=models.CharField(blank=True, default='How we help', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_ar',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_de',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_en_gb',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_es',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_fr',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_ja',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_pt',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_zh_hans',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text',
            field=models.TextField(blank=True, default='See more industries', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ar',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_de',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_en_gb',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_es',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_fr',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ja',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_pt',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_zh_hans',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_ar',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_de',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_en_gb',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_es',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_fr',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_ja',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_pt',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_zh_hans',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_ar',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_de',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_en_gb',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_es',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_fr',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_ja',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_pt',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_zh_hans',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='InternationalLocalisedFolderPage',
        ),
        migrations.DeleteModel(
            name='InternationalRegionPage',
        ),
    ]
