# Generated by Django 2.2.2 on 2019-07-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0052_auto_20190723_1147'),
        ('great_international', '0051_auto_20190722_1427_squashed_0053_auto_20190723_1029'),
    ]

    operations = [
    ]
