# Generated by Django 2.2.2 on 2019-07-23 15:00

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('great_international', '0053_auto_20190723_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
