# Generated by Django 2.2.2 on 2019-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0053_auto_20190724_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestregionpage',
            name='subsections_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
