# Generated by Django 2.2.2 on 2019-07-29 13:37

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('great_international', '0056_auto_20190725_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_text_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='case_study_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='how_dit_help_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_one_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_three_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='related_page_two_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutDitServicesPage'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_content_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditlandingpage',
            name='section_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
