# Generated by Django 2.2.3 on 2019-07-29 10:43

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('great_international', '0057_auto_20190729_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='benefits_section_cta_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_one_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_three_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_summary_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='featured_card_two_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investinternationalhomepage',
            name='teaser_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='benefits_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='capital_invest_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_call_to_action_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='contact_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_five_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_four_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_one_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_three_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_text_two_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title',
            field=models.CharField(blank=True, default='How we help', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_ar',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_de',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_en_gb',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_es',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_fr',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_ja',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_pt',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_we_help_title_zh_hans',
            field=models.CharField(blank=True, default='How we help', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='hpo_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text',
            field=models.TextField(blank=True, default='See more industries', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ar',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_de',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_en_gb',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_es',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_fr',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ja',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_pt',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_zh_hans',
            field=models.TextField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_ar',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_de',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_en_gb',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_es',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_fr',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_ja',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_pt',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_title_zh_hans',
            field=models.TextField(blank=True, default='Discover UK Industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_call_to_action_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_ar',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_de',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_en_gb',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_es',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_fr',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_ja',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_pt',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='setup_guide_title_zh_hans',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
    ]
