# Generated by Django 2.2.3 on 2019-07-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0057_auto_20190730_1356'),
        ('great_international', '0059_merge_20190729_1601'),
    ]

    operations = [
    ]
