# Generated by Django 2.2.3 on 2019-07-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0060_auto_20190730_1247'),
        ('great_international', '0057_auto_20190730_1356'),
    ]

    operations = [
    ]
