# Generated by Django 2.2.3 on 2019-08-07 08:07

import core.model_fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import great_international.panels.capital_invest


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('great_international', '0063_auto_20190806_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestContactFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('uses_tree_based_routing', models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled')),
                ('breadcrumbs_label', models.CharField(max_length=255)),
                ('breadcrumbs_label_en_gb', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_de', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_ja', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_zh_hans', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_fr', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_es', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_pt', models.CharField(max_length=255, null=True)),
                ('breadcrumbs_label_ar', models.CharField(max_length=255, null=True)),
                ('heading', models.CharField(max_length=255)),
                ('heading_en_gb', models.CharField(max_length=255, null=True)),
                ('heading_de', models.CharField(max_length=255, null=True)),
                ('heading_ja', models.CharField(max_length=255, null=True)),
                ('heading_zh_hans', models.CharField(max_length=255, null=True)),
                ('heading_fr', models.CharField(max_length=255, null=True)),
                ('heading_es', models.CharField(max_length=255, null=True)),
                ('heading_pt', models.CharField(max_length=255, null=True)),
                ('heading_ar', models.CharField(max_length=255, null=True)),
                ('intro', core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_en_gb', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_de', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_ja', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_zh_hans', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_fr', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_es', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_pt', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('intro_ar', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('cta_text', models.CharField(blank=True, max_length=255)),
                ('cta_text_en_gb', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_de', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_zh_hans', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_es', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_text_ar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(great_international.panels.capital_invest.CapitalInvestContactFormPagePanels, core.models.WagtailAdminExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
