# Generated by Django 2.2.3 on 2019-08-16 11:17

import wagtailmarkdown.fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0068_auto_20190815_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutukregionlistingpage',
            name='contact_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
