# Generated by Django 2.2.3 on 2019-08-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0070_auto_20190823_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content',
            new_name='regions_section_intro',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_ar',
            new_name='regions_section_intro_ar',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_de',
            new_name='regions_section_intro_de',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_en_gb',
            new_name='regions_section_intro_en_gb',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_es',
            new_name='regions_section_intro_es',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_fr',
            new_name='regions_section_intro_fr',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_ja',
            new_name='regions_section_intro_ja',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_pt',
            new_name='regions_section_intro_pt',
        ),
        migrations.RenameField(
            model_name='aboutuklandingpage',
            old_name='regions_section_content_zh_hans',
            new_name='regions_section_intro_zh_hans',
        ),
        migrations.RemoveField(
            model_name='aboutuklandingpage',
            name='regions_section_image',
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='midlands_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='north_england_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='northern_ireland_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='scotland_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='south_england_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuklandingpage',
            name='wales_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='great_international.AboutUkRegionPage'),
        ),
    ]
