# Generated by Django 2.2.3 on 2019-08-22 09:08

import core.model_fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0070_auto_20190820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='how_to_expand_intro_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text',
            field=models.CharField(blank=True, default='See more industries', max_length=255),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ar',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_de',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_en_gb',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_es',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_fr',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_ja',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_pt',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investinternationalhomepage',
            name='sector_button_text_zh_hans',
            field=models.CharField(blank=True, default='See more industries', max_length=255, null=True),
        ),
    ]
