# Generated by Django 2.2.4 on 2019-08-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('great_international', '0071_auto_20190823_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_ar',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_de',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_es',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_fr',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_ja',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_pt',
        ),
        migrations.RemoveField(
            model_name='internationalarticlepage',
            name='article_image_zh_hans',
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='article_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_label_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link label'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA link'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser',
            field=models.TextField(blank=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_ar',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_de',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_es',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_fr',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_ja',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_pt',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_teaser_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='CTA teaser'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='cta_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='internationalarticlepage',
            name='type_of_article',
            field=models.TextField(choices=[('blog', 'Blog'), ('advice', 'Advice'), ('case_study', 'Case study'), ('campaign', 'Campaign')], null=True),
        ),
    ]
