# Generated by Django 2.2.4 on 2019-08-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0015_auto_20190306_1521'),
        ('great_international', '0072_auto_20190827_1237'),
    ]

    operations = [
    ]
