# Generated by Django 2.2.4 on 2019-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0072_auto_20190827_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalarticlepage',
            name='type_of_article',
            field=models.TextField(choices=[('Blog', 'Blog'), ('Advice', 'Advice'), ('Case study', 'Case study'), ('Campaign', 'Campaign')], null=True),
        ),
    ]
