# Generated by Django 2.2.4 on 2019-09-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('great_international', '0073_merge_20190829_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationallocalisedfolderpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='InternationalHomePageOld',
        ),
        migrations.DeleteModel(
            name='InternationalLocalisedFolderPage',
        ),
        migrations.DeleteModel(
            name='InternationalRegionPage',
        ),
    ]
