# Generated by Django 2.2.3 on 2019-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0074_auto_20190902_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_ar',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_de',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_en_gb',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_es',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_fr',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_ja',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_pt',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='featured_description_zh_hans',
            field=models.TextField(blank=True, help_text='This will be used when this page is featured as a card on another page i.e. the About DIT landing page', null=True),
        ),
    ]
