# Generated by Django 2.2.3 on 2019-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0074_auto_20190902_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_ar',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_de',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_en_gb',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_es',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_fr',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_ja',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_pt',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitalinvestcontactformpage',
            name='comment_zh_hans',
            field=models.TextField(default='To provide you with the best help, we may forward your message to appropriate Capital Investment team colleagues in British embassies, high commissions and consulates located internationally. ', max_length=255, null=True),
        ),
    ]
