# Generated by Django 2.2.4 on 2019-09-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0074_auto_20190902_1424'),
        ('great_international', '0075_merge_20190902_1738'),
    ]

    operations = [
    ]
