# Generated by Django 2.2.4 on 2019-09-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0076_merge_20190903_1442'),
        ('great_international', '0076_auto_20190905_0812'),
    ]

    operations = [
    ]
