# Generated by Django 2.2.4 on 2019-09-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0077_auto_20190905_1334'),
        ('great_international', '0077_merge_20190905_1625'),
    ]

    operations = [
    ]
