# Generated by Django 2.2.3 on 2019-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('great_international', '0078_auto_20190906_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalHomePageOld',
        ),
    ]
