# Generated by Django 2.2.4 on 2019-09-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('great_international', '0080_auto_20190910_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='internationalregionpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='InternationalLocalisedFolderPage',
        ),
        migrations.DeleteModel(
            name='InternationalRegionPage',
        ),
    ]
