# Generated by Django 2.2.4 on 2019-09-13 09:30

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0081_auto_20190910_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text',
            field=core.model_fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_de',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_es',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='brexit_banner_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
    ]
