# Generated by Django 2.2.4 on 2019-09-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0082_auto_20190913_0930'),
        ('great_international', '0082_auto_20190913_1339'),
    ]

    operations = [
    ]
