# Generated by Django 2.2.4 on 2019-09-16 09:13

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0083_merge_20190916_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_five_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 5 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_four_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 4 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_one_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 1 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_six_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 6 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_three_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 3 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
        migrations.AlterField(
            model_name='internationalhomepage',
            name='section_two_subsection_two_heading_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, verbose_name='Features highlight 2 heading'),
        ),
    ]
