# Generated by Django 2.2.4 on 2019-09-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0085_auto_20190916_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_ar',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_de',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_en_gb',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_es',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_fr',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_ja',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_pt',
        ),
        migrations.RemoveField(
            model_name='aboutukwhychoosetheukpage',
            name='ebook_section_pdf_link_zh_hans',
        ),
    ]
