# Generated by Django 2.2.4 on 2019-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0086_auto_20190918_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukwhychoosetheukpage',
            name='hero_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
