# Generated by Django 2.2.8 on 2019-12-17 13:42

import wagtailmarkdown.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('great_international', '0090_auto_20190930_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_ar',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_de',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_es',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_fr',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_ja',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_pt',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='case_study_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_ar',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_de',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_es',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_fr',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_ja',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_pt',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='hero_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_ar',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_de',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_es',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_fr',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_ja',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_pt',
        ),
        migrations.RemoveField(
            model_name='aboutditservicespage',
            name='teaser_image_zh_hans',
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_body_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_link_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_ar',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_de',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_en_gb',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_es',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_fr',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_ja',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_pt',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutditservicespage',
            name='ebook_section_image_alt_text_zh_hans',
            field=models.CharField(blank=True, help_text='Description of image for screenreaders', max_length=255, null=True),
        ),
    ]
