# Generated by Django 2.2.24 on 2021-08-20 15:09

import wagtailmarkdown.fields
from django.db import migrations, models
import django.db.models.deletion
import great_international.blocks.investment_atlas
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('great_international', '0095_investmentatlaslandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_avatar_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_job_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_ar',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_de',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_en_gb',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_es',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_fr',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_ja',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_pt',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_link_zh_hans',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='contact_name_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='important_links_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_ar',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_de',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_en_gb',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_es',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_fr',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_ja',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_pt',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='main_content_zh_hans',
            field=wagtail.fields.StreamField([('content_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('custom_css_class', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))])), ('columns', wagtail.blocks.StreamBlock([('text', great_international.blocks.investment_atlas.MarkdownBlock())], help_text='Smaller snippets of content'))], required=False)), ('block_slug', wagtail.blocks.CharBlock(help_text="Only needed if special styling is involved: check with a developer. If in doubt, it's not needed", max_length=255, required=False))]))], blank=True, null=True),
        ),
    ]
