# Generated by Django 2.2.24 on 2021-09-03 13:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0099_merge_20210901_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_ar',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_de',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_en_gb',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_es',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_fr',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_ja',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_pt',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalhomepage',
            name='homepage_link_panels_zh_hans',
            field=wagtail.fields.StreamField([('link_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
    ]
