# Generated by Django 2.2.24 on 2021-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0102_add_new_investment_sector_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_ar',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_de',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_en_gb',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_es',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_fr',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_ja',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_pt',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalinvestmentsectorpage',
            name='early_opportunities_header_zh_hans',
            field=models.CharField(blank=True, help_text='Set to "Early investment opportunities" or customise based on the sector, as appropriate', max_length=255, null=True),
        ),
    ]
