# Generated by Django 2.2.24 on 2021-09-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('great_international', '0109_relax_early_opportunities_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_ar',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_de',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_en_gb',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_es',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_fr',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_ja',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_pt',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='mobile_hero_image_zh_hans',
            field=models.ForeignKey(blank=True, help_text='Dedicated image for use on small/mobile-screen rendering of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
