# Generated by Django 2.2.24 on 2021-09-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('great_international', '0110_auto_20210909_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_ar',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_de',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_en_gb',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_es',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_fr',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_ja',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_pt',
        ),
        migrations.RemoveField(
            model_name='investmentopportunitypage',
            name='featured_images_zh_hans',
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_ar',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_de',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_en_gb',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_es',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_fr',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_ja',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_pt',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='hero_image_zh_hans',
            field=models.ForeignKey(blank=True, help_text='Main page hero image, above the opportunity title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_ar',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_de',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_en_gb',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_es',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_fr',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_ja',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_pt',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='intro_image_zh_hans',
            field=models.ForeignKey(blank=True, help_text='Goes beside the opportunity intro text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
