# Generated by Django 2.2.24 on 2021-09-14 13:28

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0113_sector_page_downpage_content_streamblock_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_intro_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='investment_opps_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_intro_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='region_summary_section_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_intro_zh_hans',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_ar',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_de',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_en_gb',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_es',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_fr',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_ja',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_pt',
        ),
        migrations.RemoveField(
            model_name='whyinvestintheukpage',
            name='uk_sector_section_title_zh_hans',
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='featured_summary_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_ar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_de',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_en_gb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_es',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_fr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_ja',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_pt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_intro_zh_hans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_ar',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_de',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_en_gb',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_es',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_fr',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_ja',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_pt',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_panels_zh_hans',
            field=wagtail.fields.StreamField([('article_panel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('supporting_text', wagtail.blocks.TextBlock(max_length=1000, required=False)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(label='Internal link', required=False)), ('external_link', wagtail.blocks.CharBlock(label='External link', max_length=255, required=False))], required=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_alt', wagtail.blocks.CharBlock(max_length=255, required=True)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))], required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyinvestintheukpage',
            name='uk_strength_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
