# Generated by Django 2.2.24 on 2021-09-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0115_merge_20210914_1442'),
        ('great_international', '0115_split_region_page_intro_into_strapline_and_intro'),
    ]

    operations = [
    ]
