# Generated by Django 2.2.24 on 2021-09-16 15:29

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0118_refactor_whyinvestintheuk_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyinvestintheukpage',
            name='introduction',
            field=core.model_fields.MarkdownField(null=True),
        ),
    ]
