# Generated by Django 2.2.24 on 2021-09-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0121_extending_regional_detail_page_intro_character_limit'),
        ('great_international', '0118_rename_investhighpotentialopportunityform'),
    ]

    operations = [
    ]
