# Generated by Django 2.2.24 on 2021-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0123_add_expandable_trigger_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_de',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_en_gb',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_es',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_fr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_ja',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_pt',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
