# Generated by Django 2.2.24 on 2021-09-24 15:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0124_increase_length_of_region_case_study_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='location_coords',
            field=wagtail.core.fields.StreamField([('map_location', wagtail.core.blocks.StructBlock([('region', wagtail.core.blocks.PageChooserBlock(label='Regions', pagg_type='great_international.AboutUkRegionPage', required=False)), ('location_coords', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True),
        ),
    ]
