# Generated by Django 2.2.24 on 2021-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0125_adding_map_coordinates_for_opportunity_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttype',
            name='name',
            field=models.CharField(max_length=99),
        ),
    ]
