# Generated by Django 2.2.24 on 2021-10-04 10:43

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0127_auto_20211001_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text',
            field=core.model_fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_de',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_es',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='case_study_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
    ]
