# Generated by Django 2.2.24 on 2021-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0128_auto_20211004_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutukregionpage',
            name='region_summary_section_intro_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
