# Generated by Django 2.2.24 on 2021-11-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('great_international', '0139_auto_20211013_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalCuratedTopicLandingPage',
        ),
    ]
