# Generated by Django 2.2.24 on 2021-10-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0139_auto_20211013_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header',
            new_name='other_opportunities_header',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_ar',
            new_name='other_opportunities_header_ar',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_de',
            new_name='other_opportunities_header_de',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_en_gb',
            new_name='other_opportunities_header_en_gb',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_es',
            new_name='other_opportunities_header_es',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_fr',
            new_name='other_opportunities_header_fr',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_ja',
            new_name='other_opportunities_header_ja',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_pt',
            new_name='other_opportunities_header_pt',
        ),
        migrations.RenameField(
            model_name='internationalinvestmentsectorpage',
            old_name='related_opportunities_header_zh_hans',
            new_name='other_opportunities_header_zh_hans',
        ),
    ]
