# Generated by Django 2.2.24 on 2021-12-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('great_international', '0143_delete_capitalinvestopportunitylistingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapitalInvestRegionPage',
        ),
    ]
