# Generated by Django 2.2.28 on 2022-07-19 10:25

from django.db import migrations, models
import great_international.validators
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0154_auto_20220111_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_ar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_de',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_en_gb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_es',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_fr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_ja',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_pt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_link_zh_hans',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentatlaslandingpage',
            name='hero_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentopportunitypage',
            name='regions_with_locations',
            field=wagtail.core.fields.StreamField([('location', wagtail.core.blocks.StructBlock([('region', wagtail.core.blocks.PageChooserBlock(label='Linked Region', page_type=['great_international.AboutUkRegionPage'], required=False)), ('map_coordinate', wagtail.core.blocks.CharBlock(help_text='Latitude and longitude Coordinates, e.g. 176.0944492, -38.50245621', label='Linked Location Coordinates', max_length=200, validators=[great_international.validators.validate_lat_long]))]))], blank=True, null=True),
        ),
    ]
