# Generated by Django 2.2.28 on 2022-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('great_international', '0155_auto_20220719_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaleuexitformsuccesspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='InternationalEUExitFormPage',
        ),
        migrations.DeleteModel(
            name='InternationalEUExitFormSuccessPage',
        ),
    ]
