# Generated by Django 2.2.28 on 2022-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_international', '0157_add_intro_video_to_investment_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_ar',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_de',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_en_gb',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_es',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_fr',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_ja',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_pt',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investmentopportunitypage',
            name='get_related_opportunities_by_zh_hans',
            field=models.CharField(choices=[('INVESTMENT_TYPE', 'Investment type'), ('RELATED_SECTORS', 'Related sectors')], default='RELATED_SECTORS', help_text='Used to determine what related opportunities are dislayed on the page.', max_length=50, null=True),
        ),
    ]
