# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 10:18
from __future__ import unicode_literals

import core.fields
import core.validators
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=core.fields.MarkdownField(validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks, core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='pullout',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('text', wagtailmarkdown.blocks.MarkdownBlock()), ('stat', wagtail.core.blocks.CharBlock()), ('stat_text', wagtail.core.blocks.CharBlock())), max_num=1, min_num=0)),), blank=True, null=True),
        ),
    ]
