# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 13:45
from __future__ import unicode_literals

from django.db import migrations


def migrate_sector_page_streamfields(apps, schema_editor):
    SectorPage = apps.get_model('invest', 'SectorPage')
    pages = SectorPage.objects.all()
    for page in pages:
        pass



def migrate_setup_guide_page_streamfields(apps, schema_editor):
    SetupGuidePage = apps.get_model('invest', 'SetupGuidePage')
    pages = SetupGuidePage.objects.all()
    for page in pages:
        pass


def migrate_home_page_streamfields(apps, schema_editor):
    HomePage = apps.get_model('invest', 'HomePage')
    pages = HomePage.objects.all()


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20180716_1343'),
    ]

    operations = [

    ]
