# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 13:01
from __future__ import unicode_literals

import core.fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20180717_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_five_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_four_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_one_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_seven_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_six_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_three_zh_hans',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_ar',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_de',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_en_gb',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_es',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_fr',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_ja',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_pt',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_pt_br',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_ru',
        ),
        migrations.RemoveField(
            model_name='sectorpage',
            name='subsection_info_two_zh_hans',
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='how_we_help_url_six_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one',
            field=core.fields.MarkdownField(validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_one_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two',
            field=core.fields.MarkdownField(validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='subsection_content_two_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
