# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_squashed_0006_auto_20180719_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_ar',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_de',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_en_gb',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_es',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_fr',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_ja',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_pt',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_pt_br',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_ru',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='how_we_help_url_six_zh_hans',
        ),
    ]
