# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 13:46
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import invest.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('invest', '0008_auto_20180817_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighPotentialOpportunityFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('comment_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('comment_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('company_name_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('company_name_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('company_size_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('company_size_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('country_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('country_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('email_address_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('email_address_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('full_name_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('full_name_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('opportunities_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('opportunities_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('phone_number_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('phone_number_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('role_in_company_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('role_in_company_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('terms_agreed_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('terms_agreed_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
                ('website_url_help_text', invest.models.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('website_url_label', invest.models.FormLabelField(max_length=200, verbose_name='label')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
