# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_auto_20180817_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='investapp',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, default='INVEST', max_length=100),
            preserve_default=False,
        ),
    ]
