# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_highpotentialofferformpage'),
        ('invest', '0009_investapp_service_name'),
    ]

    operations = [
    ]
