# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_merge_20180829_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investapp',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
    ]
