# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_auto_20180725_1311'),
        ('invest', '0011_auto_20180829_1027'),
    ]

    operations = [
    ]
