# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0016_auto_20180911_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunityformpage',
            name='heading',
            field=models.CharField(default='Your business details', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highpotentialopportunityformpage',
            name='sub_heading',
            field=models.CharField(default='The questions below will help us provide the best support for you', max_length=255),
            preserve_default=False,
        ),
    ]
