# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 14:45
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('invest', '0017_auto_20190206_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_pt_br',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_ru',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_content_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefits section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_img_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Benefits section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title',
            field=models.CharField(default='Benefits', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label',
            field=models.CharField(default='Invest', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text',
            field=models.CharField(default='Get in touch', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title',
            field=models.CharField(default='Contact us', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section button text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_pt_br',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_ru',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_content_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='EU exit section content'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU Exit section image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_img_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='EU exit section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EU exit section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro',
            field=models.TextField(blank=True, max_length=255, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='High potential opportunity section intro'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title',
            field=models.CharField(default='High potential opportunities', max_length=255, verbose_name='High potential opportunity section title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='High potential opportunity section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text',
            field=models.CharField(default='Set up now', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_text_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_pt_br',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_ru',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup guide image caption'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_pt_br',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='how_we_help_text_six_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_pt_br',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_ru',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_one_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_pt_br',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_ru',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_content_two_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_one_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='subsection_title_two_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
