# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0018_auto_20180913_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunityformpage',
            name='breadcrumbs_label',
            field=models.CharField(default='Contact us', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highpotentialopportunitydetailpage',
            name='summary_image',
            field=models.ForeignKey(blank=True, help_text='Image used on the opportunity listing page for this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
    ]
