# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:26
from __future__ import unicode_literals

import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0019_auto_20180917_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highpotentialopportunitydetailpage',
            name='opportunity_list_item_three',
            field=core.fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
