# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0020_auto_20190402_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_pt_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
