# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0021_auto_20190314_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text',
            field=models.CharField(default='Contact Us', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_text_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_content_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title',
            field=models.CharField(default='Contact', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
