# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0022_auto_20190314_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
