# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0022_auto_20190411_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='highpotentialopportunityformpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='highpotentialopportunityformsuccesspage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='investapp',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='regionlandingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='sectorlandingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='sectorpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
    ]
