# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0022_auto_20190405_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url',
            field=models.URLField(default='http://invest.trade.great:8012/contact/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_ar',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_de',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_en_gb',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_es',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_fr',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_ja',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_pt',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_pt_br',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_ru',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_zh_hans',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url',
            field=models.URLField(default='http://invest.trade.great:8012/contact/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_ar',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_de',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_en_gb',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_es',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_fr',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_ja',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_pt',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_pt_br',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_ru',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='contact_section_call_to_action_url_zh_hans',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_ar',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_de',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_en_gb',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_es',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_fr',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_ja',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_pt',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_pt_br',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_ru',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='eu_exit_section_call_to_action_url_zh_hans',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='EU exit section button url'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_ar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_de',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_en_gb',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_es',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_fr',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_ja',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_pt',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_pt_br',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_ru',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hero_call_to_action_url_zh_hans',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url',
            field=models.URLField(default='http://invest.trade.great:8012/industries', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_ar',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_de',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_en_gb',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_es',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_fr',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_ja',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_pt',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_pt_br',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_ru',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='sector_button_url_zh_hans',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url',
            field=models.URLField(default='setup', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_ar',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_de',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_en_gb',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_es',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_fr',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_ja',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_pt',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_pt_br',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_ru',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_zh_hans',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
