# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('invest', '0023_auto_20180918_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='highpotentialopportunitydetailpage',
            name='testimonial_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Background image'),
        ),
    ]
