# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0024_auto_20190417_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_ar',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_de',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_en_gb',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_es',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_fr',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_ja',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_pt',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_background_image_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_ar',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_de',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_en_gb',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_es',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_fr',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_ja',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_pt',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_text_zh_hans',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_ar',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_de',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_en_gb',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_es',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_fr',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_ja',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_pt',
        ),
        migrations.RemoveField(
            model_name='investhomepage',
            name='capital_invest_section_cta_url_zh_hans',
        ),
    ]
