# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0025_auto_20190318_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_en_gb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ja',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_pt',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_pt_br',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_intro_zh_hans',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title',
            field=models.CharField(default='HPO', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='hpo_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
