# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 11:41
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('invest', '0031_auto_20190529_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_content_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='capital_invest_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_image_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Investment Support Directory section image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_ar',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_de',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_en_gb',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_es',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_fr',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_ja',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_pt',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_text_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, max_length=255, null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Investment Support Directory section text'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='isd_section_title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Support Directory section title'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_call_to_action_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content',
            field=core.model_fields.MarkdownField(blank=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_ar',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_de',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_en_gb',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_es',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_fr',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_ja',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_pt',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_content_zh_hans',
            field=core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_en_gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_img_zh_hans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Setup guide image'),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_lead_in_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_ar',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_de',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_en_gb',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_es',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_fr',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_ja',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_pt',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='setup_guide_title_zh_hans',
            field=models.CharField(blank=True, default='Set up an overseas business in the UK', max_length=255, null=True),
        ),
    ]
