# Generated by Django 2.2.3 on 2019-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0032_auto_20190605_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_text_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='benefits_section_cta_url_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investhomepage',
            name='teaser_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
