# Generated by Django 2.2.2 on 2019-07-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('invest', '0032_auto_20190605_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPage',
        ),
    ]
