# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 11:42
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('export_readiness', '0003_exportreadinessapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyAndCookiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('privacy_title', models.CharField(max_length=255)),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_ar',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_de',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_en_gb',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_es',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_fr',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_ja',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_pt',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_pt_br',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='body_zh_hans',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_ar',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_de',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_en_gb',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_es',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_fr',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_ja',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_pt',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_pt_br',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_ru',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='terms_title_zh_hans',
        ),
    ]
