# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 11:11
from __future__ import unicode_literals

import html2text
from wagtail.wagtailcore.models import Orderable
from wagtail.wagtailcore.rich_text import expand_db_html
from wagtail.wagtailcore.fields import RichTextField
from wagtailmarkdown.fields import MarkdownField

from django.db import migrations


def html_to_markdown(apps, schema_editor):
    class_names = ['TermsAndConditionsPage', 'PrivacyAndCookiesPage']
    for class_name in class_names:
        model_class = apps.get_model('export_readiness', class_name)
        field_names = []
        for field in model_class._meta.get_fields():
            if (
                isinstance(field, RichTextField) or
                isinstance(field, MarkdownField)
            ):
                field_names.append(field.name)
        for page in model_class.objects.all():
            for field_name in field_names:
                html = expand_db_html(getattr(page, field_name))
                markdown = html2text.html2text(html).strip()
                setattr(page, field_name, markdown)
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0004_auto_20180423_1142'),
    ]

    operations = [
        migrations.RunPython(html_to_markdown, migrations.RunPython.noop)
    ]
