# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 14:29
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('export_readiness', '0006_auto_20180427_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetFinancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('banner_content', core.api_fields.MarkdownField()),
                ('section_one_content', core.api_fields.MarkdownField()),
                ('section_two_content', core.api_fields.MarkdownField()),
                ('video_embed', models.CharField(max_length=500)),
                ('section_three_content', core.api_fields.MarkdownField()),
                ('call_to_action_text', models.CharField(max_length=255)),
                ('call_to_action_url', models.CharField(max_length=500)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('ukef_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
