# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 14:30
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0008_performancedashboardpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedashboardpage',
            name='guidance_notes',
            field=core.api_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
