# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0011_auto_20180817_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getfinancepage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='performancedashboardnotespage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='privacyandcookiespage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='termsandconditionspage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
    ]
