# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20180829_0939'),
        ('export_readiness', '0014_auto_20180829_1027'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        )
    ]
