# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0015_auto_20180830_0632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetFinancePage',
            new_name='DeprecatedGetFinancePage',
        ),
    ]
