# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 10:22
from __future__ import unicode_literals

from django.db import migrations


def rename_deprecated_get_finance_slug(apps, schema_editor):
    DeprecatedGetFinancePage = apps.get_model(
        'export_readiness', 'DeprecatedGetFinancePage'
    )

    for page in DeprecatedGetFinancePage.objects.all():
        page.slug = 'get-finance-deprecated'
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0016_auto_20180905_1020'),
    ]

    operations = [
        migrations.RunPython(
           rename_deprecated_get_finance_slug,
           reverse_code=migrations.RunPython.noop,
            elidable=True
        )
    ]
