# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('export_readiness', '0014_auto_20180829_1027_squashed_0018_getfinancepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgetfinancepage',
            name='advantages_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='newgetfinancepage',
            name='advantages_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='newgetfinancepage',
            name='advantages_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
