# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 13:46
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('export_readiness', '0019_auto_20180905_1350'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('landing_page_title', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('list_teaser', core.api_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('article_title', models.CharField(max_length=255)),
                ('article_teaser', models.CharField(max_length=255)),
                ('article_body_text', core.api_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('related_article_one_url', models.CharField(help_text='Paste the article path here (eg /foo/bar/)', max_length=255)),
                ('related_article_one_title', models.CharField(help_text='Paste the title of the article here', max_length=255)),
                ('related_article_one_teaser', models.CharField(help_text='Paste the article description here (max 255 characters)', max_length=255)),
                ('related_article_two_url', models.CharField(help_text='Paste the article path here (eg /foo/bar/)', max_length=255)),
                ('related_article_two_title', models.CharField(help_text='Paste the title of the article here', max_length=255)),
                ('related_article_two_teaser', models.CharField(help_text='Paste the article description here (max 255 characters)', max_length=255)),
                ('related_article_three_url', models.CharField(help_text='Paste the article path here (eg /foo/bar/)', max_length=255)),
                ('related_article_three_title', models.CharField(help_text='Paste the title of the article here', max_length=255)),
                ('related_article_three_teaser', models.CharField(help_text='Paste the article description here (max 255 characters)', max_length=255)),
                ('article_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('landing_page_title', models.CharField(max_length=255)),
                ('hero_teaser', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='newgetfinancepage',
            name='evidence_video_embed',
        ),
        migrations.AddField(
            model_name='newgetfinancepage',
            name='evidence_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', core.api_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EUExitInternationalFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('first_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('first_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('last_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('last_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('email_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('email_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('organisation_type_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('organisation_type_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('company_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('company_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('country_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('country_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('city_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('city_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('comment_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('comment_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('body_text', core.api_fields.MarkdownField(default='', validators=[core.validators.slug_hyperlinks])),
                ('heading', models.CharField(default='', max_length=255)),
                ('submit_button_text', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=255)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.CreateModel(
            name='EUExitDomesticFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('first_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('first_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('last_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('last_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('email_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('email_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('organisation_type_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('organisation_type_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('company_name_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('company_name_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('comment_help_text', core.api_fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text')),
                ('comment_label', core.api_fields.FormLabelField(max_length=200, verbose_name='label')),
                ('body_text', core.api_fields.MarkdownField(default='', validators=[core.validators.slug_hyperlinks])),
                ('heading', models.CharField(default='', max_length=255)),
                ('submit_button_text', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EUExitFormSuccessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255, verbose_name='Title')),
                ('body_text', models.CharField(max_length=255, verbose_name='Body text')),
                ('next_title', models.CharField(max_length=255, verbose_name='Title')),
                ('next_body_text', models.CharField(max_length=255, verbose_name='Body text')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_one_teaser',
            field=models.CharField(blank=True, help_text='Paste the article description here (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_one_title',
            field=models.CharField(blank=True, help_text='Paste the title of the article here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_one_url',
            field=models.CharField(blank=True, help_text='Paste the article path here (eg /foo/bar/)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_three_teaser',
            field=models.CharField(blank=True, help_text='Paste the article description here (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_three_title',
            field=models.CharField(blank=True, help_text='Paste the title of the article here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_three_url',
            field=models.CharField(blank=True, help_text='Paste the article path here (eg /foo/bar/)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_two_teaser',
            field=models.CharField(blank=True, help_text='Paste the article description here (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_two_title',
            field=models.CharField(blank=True, help_text='Paste the title of the article here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='related_article_two_url',
            field=models.CharField(blank=True, help_text='Paste the article path here (eg /foo/bar/)', max_length=255, null=True),
        ),
    ]
