# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 12:02
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0022_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='list_teaser',
            field=core.api_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
    ]
