# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0023_auto_20181001_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
    ]
