# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0025_auto_20181002_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
