# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0027_auto_20181004_1207'),
        ('export_readiness', '0026_euexitdomesticformpage'),
    ]

    operations = [
    ]
