# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 14:33
from __future__ import unicode_literals

import core.fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0027_auto_20181003_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='body_text',
            field=core.fields.MarkdownField(default='', validators=[core.validators.slug_hyperlinks]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
