# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:03
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('export_readiness', '0028_merge_20181004_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUExitFormSuccessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True)),
                ('breadcrumbs_label', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255, verbose_name='Title')),
                ('body_text', models.CharField(max_length=255, verbose_name='Body text')),
                ('next_title', models.CharField(max_length=255, verbose_name='Title')),
                ('next_body_text', models.CharField(max_length=255, verbose_name='Body text')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='body_text',
            field=core.api_fields.MarkdownField(default='', validators=[core.validators.slug_hyperlinks]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='submit_button_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='body_text',
            field=core.api_fields.MarkdownField(default='', validators=[core.validators.slug_hyperlinks]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='submit_button_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
