# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 15:07
from __future__ import unicode_literals

import core.api_fields
import core.fields
import core.model_fields
import core.validators
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0031_internationallandingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.Tag'),
        ),
        migrations.AlterField(
            model_name='euexitdomesticformpage',
            name='body_text',
            field=core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='euexitdomesticformpage',
            name='heading',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='euexitdomesticformpage',
            name='submit_button_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='euexitinternationalformpage',
            name='body_text',
            field=core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='euexitinternationalformpage',
            name='heading',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='euexitinternationalformpage',
            name='submit_button_text',
            field=models.CharField(max_length=50),
        ),
    ]
