# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 10:27
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0032_auto_20181012_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='terms_agreed_help_text',
            field=core.fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='terms_agreed_label',
            field=core.fields.FormLabelField(default='', max_length=200, verbose_name='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='terms_agreed_help_text',
            field=core.fields.FormHelpTextField(blank=True, max_length=200, null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='terms_agreed_label',
            field=core.fields.FormLabelField(default='', max_length=200, verbose_name='label'),
            preserve_default=False,
        ),
    ]
