# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 15:57
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('export_readiness', '0032_auto_20190307_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryguidepage',
            old_name='landing_page_title',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='countryguidepage',
            old_name='related_content_heading',
            new_name='statistic_1_heading',
        ),
        migrations.RenameField(
            model_name='countryguidepage',
            old_name='selling_point_one_heading',
            new_name='statistic_1_number',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='related_content_intro',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='section_one_content',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='section_one_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='section_two_content',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_one_content',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_one_icon',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_three_content',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_three_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_three_icon',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_two_content',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_two_heading',
        ),
        migrations.RemoveField(
            model_name='countryguidepage',
            name='selling_point_two_icon',
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_1_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_2_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_3_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_4_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_5_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion hero'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Accordion Icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_1_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 1 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_2_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 2 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_3_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 3 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_4_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_4_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 4 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_5_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_5_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 5 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_6_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_6_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 number'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stat 6 smallprint'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_1_body',
            field=models.TextField(blank=True, verbose_name='Subsection 1 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_1_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 1 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 1 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_2_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_2_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_3_body',
            field=models.TextField(blank=True, verbose_name='Subsection 2 body'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_3_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subsection 2 heading'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_subsection_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Subsection 2 icon'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_teaser',
            field=models.TextField(blank=True, verbose_name='Accordion teaser'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='accordion_6_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accordion title'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='heading_teaser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='section_one_body',
            field=core.model_fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks], verbose_name='Bullets markdown'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='section_one_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bullets image'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='section_one_image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='section_one_image_caption_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bullets image caption — company name'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='section_two_teaser',
            field=models.TextField(default='', verbose_name='Highlights teaser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_1_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_2_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_2_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_2_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_3_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_3_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_3_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_4_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_4_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_4_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_5_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_5_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_5_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_6_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_6_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='statistic_6_smallprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_two_heading',
            field=models.CharField(max_length=255, verbose_name='Highlights heading'),
        ),
    ]
