# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 10:28
from __future__ import unicode_literals

import core.api_fields
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('export_readiness', '0034_auto_20181024_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOpportunitiesGuidancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components')], db_index=True, max_length=100, null=True)),
                ('daily_alerts_not_relavant', core.api_fields.MarkdownField(validators=[core.validators.slug_hyperlinks], verbose_name='Guidance')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ExclusivePageMixin, 'wagtailcore.page'),
        ),
    ]
