# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 07:28
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0036_topiclandingpage_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_1_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_1_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_2_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_2_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_3_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_3_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_4_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_4_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_4_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_5_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_5_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_5_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_6_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Industry Icon'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_6_teaser',
            field=models.TextField(blank=True, verbose_name='Industry teaser'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='accordion_6_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industry title'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_1_body',
            field=core.model_fields.MarkdownField(blank=True, help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.', validators=[core.validators.slug_hyperlinks], verbose_name="Detailed text for 'Tax and customs'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_1_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name="Summary for 'Tax and customs'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_1_title',
            field=models.CharField(blank=True, max_length=255, verbose_name="Title for 'Tax and customs'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_2_body',
            field=core.model_fields.MarkdownField(blank=True, help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.', validators=[core.validators.slug_hyperlinks], verbose_name="Detailed text for 'Protecting your business'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_2_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name="Summary for 'Protecting your business'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_2_title',
            field=models.CharField(blank=True, max_length=255, verbose_name="Title for 'Protecting your business'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_teaser',
            field=models.CharField(blank=True, max_length=255, verbose_name="Summary for 'Doing business in' section"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_title',
            field=models.CharField(blank=True, max_length=255, verbose_name="Title for 'Doing business in' section"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='heading',
            field=models.CharField(help_text='Only enter the country name', max_length=255, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='heading_teaser',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='help_market_guide_cta_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='GOV.UK country guide URL'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_one_body',
            field=core.model_fields.MarkdownField(help_text='Use H3 (###) markdown for the 3 subheadings', null=True, validators=[core.validators.slug_hyperlinks], verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_one_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for unique selling points'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_two_heading',
            field=models.CharField(max_length=255, verbose_name='High potential industries for UK businesses'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_two_teaser',
            field=models.TextField(verbose_name='Summary of the industry opportunities'),
        ),
    ]
