# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0037_auto_20181106_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewGetFinancePage',
            new_name='GetFinancePage',
        ),
    ]
