# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0040_auto_20190411_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcontactpagespage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='articlelistingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='contactsuccesspage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='contactsuccesspages',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='contactusguidancepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='contactusguidancepages',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='euexitdomesticformpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='euexitformpages',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='euexitformsuccesspage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='euexitinternationalformpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='exportreadinessapp',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='getfinancepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='internationallandingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='marketingpages',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='performancedashboardnotespage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='performancedashboardpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='privacyandcookiespage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='sitepolicypages',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='termsandconditionspage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
        migrations.AddField(
            model_name='topiclandingpage',
            name='uses_tree_based_routing',
            field=models.BooleanField(default=False, help_text="Allow this page's URL to be determined by its slug, and the slugs of its ancestors in the page tree.", verbose_name='tree-based routing enabled'),
        ),
    ]
