# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 14:13
from __future__ import unicode_literals

import core.model_fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('export_readiness', '0042_contactsuccesspages_contactusguidancepages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components')], db_index=True, max_length=100, null=True)),
                ('landing_page_title', models.CharField(max_length=255)),
                ('section_one_heading', models.CharField(max_length=50)),
                ('section_one_content', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('selling_point_one_heading', models.CharField(max_length=255)),
                ('selling_point_one_content', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('selling_point_two_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_two_content', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('selling_point_three_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point_three_content', core.model_fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks])),
                ('section_two_heading', models.CharField(max_length=255)),
                ('section_two_content', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('related_content_heading', models.CharField(max_length=255)),
                ('related_content_intro', core.model_fields.MarkdownField(validators=[core.validators.slug_hyperlinks])),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SuperregionPage',
            fields=[
                ('topiclandingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='export_readiness.TopicLandingPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('export_readiness.topiclandingpage',),
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_one_teaser',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_one_title',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_one_url',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_three_teaser',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_three_title',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_three_url',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_two_teaser',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_two_title',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='related_article_two_url',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_one_description',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_one_heading',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_one_image',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_one_url',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_three_description',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_three_heading',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_three_image',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_three_url',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_two_description',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_two_heading',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_two_image',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='related_page_two_url',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='related_page_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='related_page_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='related_page_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='export_readiness.ArticlePage'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='selling_point_one_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='selling_point_three_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='selling_point_two_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
