# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:20
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace

OLD_SLUG = 'export-readiness-app'
OLD_URL_PATH = '/' + OLD_SLUG + '/'
NEW_SLUG = 'great-domestic-home'
NEW_URL_PATH = '/' + NEW_SLUG + '/'


def clear_site_root_cache():
    from django.core.cache import cache
    cache.delete('wagtail_site_root_paths')


def migrate_forwards(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    for page in Page.objects.filter(slug=OLD_SLUG):
        page.slug = NEW_SLUG
        page.save()
        clear_site_root_cache()

    Page.objects.filter(url_path__startswith=OLD_URL_PATH).update(
        url_path=Replace('url_path', Value(OLD_URL_PATH), Value(NEW_URL_PATH)))


def migrate_backwards(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    for page in Page.objects.filter(slug=NEW_SLUG):
        page.slug = OLD_SLUG
        page.save()
        clear_site_root_cache()

    Page.objects.filter(url_path__startswith=NEW_URL_PATH).update(
        url_path=Replace('url_path', Value(NEW_URL_PATH), Value(OLD_URL_PATH)))


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0047_correct_page_contenttypes'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards),
    ]
