# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0049_auto_20190207_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusguidancepage',
            name='topic',
            field=models.TextField(choices=[('alerts-not-relevant', 'Guidance - Daily alerts are not relevant'), ('opportunity-no-response', 'Guidance - Export Opportunity application no response'), ('no-verification-email', 'Guidance - Email verification missing'), ('password-reset', 'Guidance - Missing password reset link'), ('companies-house-login', 'Guidance - Companies House login not working'), ('verification-letter-code', 'Guidance - Where to enter letter verification code'), ('no-verification-letter', 'Guidance - Verification letter not delivered'), ('verification-missing', 'Guidance - Verification code not delivered'), ('company-not-found', 'Guidance - Company not found')], help_text='The slug and CMS page title are inferred from the topic', unique=True),
        ),
    ]
