# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:20
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace

OLD_SLUG = 'export-readiness-app'
OLD_URL_PATH_START = '/' + OLD_SLUG + '/'
NEW_SLUG = 'great-domestic-home'
NEW_URL_PATH_START = '/' + NEW_SLUG + '/'


def migrate_forwards(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    Page.objects.filter(slug=OLD_SLUG).update(slug=NEW_SLUG)
    Page.objects.filter(url_path__startswith=OLD_URL_PATH_START).update(
        name=Replace('url_path', Value(OLD_URL_PATH_START), Value(NEW_URL_PATH_START)))


def migrate_backwards(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    Page.objects.filter(slug=NEW_SLUG).update(slug=OLD_SLUG)
    Page.objects.filter(url_path__startswith=NEW_URL_PATH_START).update(
        name=Replace('url_path', Value(NEW_URL_PATH_START), Value(OLD_URL_PATH_START)))


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0050_auto_20190219_1633'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards),
    ]
