# Generated by Django 2.2.2 on 2019-07-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('export_readiness', '0051_auto_20190627_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationallandingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EUExitInternationalFormPage',
        ),
        migrations.DeleteModel(
            name='InternationalLandingPage',
        ),
    ]
