# Generated by Django 2.2.4 on 2019-08-23 10:36

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0051_auto_20190627_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='list_teaser',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='article_body_text',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='related_content_intro',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='section_one_intro',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='section_two_intro',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_one_content',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_three_content',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='selling_point_two_content',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactusguidancepage',
            name='body',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_1_body',
            field=core.model_fields.MarkdownField(blank=True, help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.', verbose_name="Detailed text for 'Tax and customs'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='fact_sheet_column_2_body',
            field=core.model_fields.MarkdownField(blank=True, help_text='Use H4 (####) for each sub category heading. Maximum five sub categories. Aim for 50 words each.', verbose_name="Detailed text for 'Protecting your business'"),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_one_body',
            field=core.model_fields.MarkdownField(help_text='Use H3 (###) markdown for the 3 subheadings', null=True, verbose_name='3 unique selling points markdown'),
        ),
        migrations.AlterField(
            model_name='euexitdomesticformpage',
            name='body_text',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='euexitinternationalformpage',
            name='body_text',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='advantages_one',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='advantages_three',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='advantages_two',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='contact_proposition',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='evidence',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='getfinancepage',
            name='hero_text',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_content',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_description',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='homepageold',
            name='banner_content',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='homepageold',
            name='news_description',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='marketingarticlepage',
            name='article_body_text',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='performancedashboardnotespage',
            name='body',
            field=core.model_fields.MarkdownField(help_text='Please include an h1 in this field e.g. # Heading level 1'),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_description_row_four',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_description_row_one',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_description_row_three',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_description_row_two',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='description',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='guidance_notes',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacyandcookiespage',
            name='body',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='termsandconditionspage',
            name='body',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='topiclandingpage',
            name='banner_text',
            field=core.model_fields.MarkdownField(blank=True),
        ),
    ]
