# Generated by Django 2.2.4 on 2019-09-10 10:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('export_readiness', '0054_auto_20190830_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_dit_helps_columns',
            field=wagtail.core.fields.StreamField([('columns', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_dit_helps_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='questions',
            field=wagtail.core.fields.StreamField([('questions', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='questions_section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_is_new_pages',
            field=wagtail.core.fields.StreamField([('pages', wagtail.core.blocks.PageChooserBlock(page_type=['export_readiness.ArticlePage']))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_is_new_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
