# Generated by Django 2.2.4 on 2019-09-10 13:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0055_auto_20190910_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='how_dit_helps_columns',
            field=wagtail.core.fields.StreamField([('columns', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
