# Generated by Django 2.2.4 on 2019-09-12 13:26

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0056_auto_20190910_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='export_readiness.IndustryTag'),
        ),
    ]
