# Generated by Django 2.2.4 on 2019-09-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('export_readiness', '0058_auto_20190912_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageold',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='internationallandingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EUExitInternationalFormPage',
        ),
        migrations.DeleteModel(
            name='HomePageOld',
        ),
        migrations.DeleteModel(
            name='InternationalLandingPage',
        ),
    ]
