# Generated by Django 2.2.4 on 2019-09-19 16:08

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0060_homepage_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='article_video_transcript',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
    ]
