# Generated by Django 2.2.4 on 2019-10-08 13:07

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0062_industrytag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='chevron_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.StructBlock([('source', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chevron_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chevron_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
