# Generated by Django 2.2.4 on 2019-10-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0064_merge_20191009_1320'),
        ('export_readiness', '0064_auto_20191009_1050'),
    ]

    operations = [
    ]
