# Generated by Django 2.2.4 on 2019-10-15 10:54

import core.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0065_merge_20191009_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='campaign',
            field=wagtail.fields.StreamField([('campaign', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock()), ('related_link_text', wagtail.blocks.CharBlock()), ('related_link_url', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', core.blocks.VideoChooserBlock()), ('video_transcript', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='chevron_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.StructBlock([('source', wagtail.blocks.CharBlock(help_text='The source or the type of the link, e.g. GOV.UK/Advice')), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='how_dit_helps_columns',
            field=wagtail.fields.StreamField([('columns', wagtail.blocks.StructBlock([('source', wagtail.blocks.CharBlock(help_text='The source or the type of the link, e.g. GOV.UK/Advice')), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='what_is_new_pages',
            field=wagtail.fields.StreamField([('pages', wagtail.blocks.StructBlock([('source', wagtail.blocks.CharBlock(help_text='The source or the type of the link, e.g. GOV.UK/Advice')), ('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_alt', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
