# Generated by Django 2.2.4 on 2019-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0066_auto_20191015_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_two_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='High potential industries for UK businesses'),
        ),
        migrations.AlterField(
            model_name='countryguidepage',
            name='section_two_teaser',
            field=models.TextField(blank=True, verbose_name='Summary of the industry opportunities'),
        ),
    ]
