# Generated by Django 2.2.6 on 2020-02-03 13:33

import logging


import core.model_fields
from django.db import migrations, models

import pycountry


logger = logging.getLogger(__name__)


def set_duties_and_custom_procedures_cta_link(apps, schema_editor):
    url = 'https://www.check-duties-customs-exporting-goods.service.gov.uk/searchproduct?d='
    CountryGuidePage = apps.get_model('export_readiness', 'CountryGuidePage')
    for guide in CountryGuidePage.objects.all():
        try:
            matches = pycountry.countries.search_fuzzy(guide.country.name)
        except LookupError:
            logger.warn(f'no country match for {guide.country.name}')
        except AttributeError:
            logger.warn(f'skipping {guide.title}')
        else:
            guide.duties_and_custom_procedures_cta_link = f'{url}{matches[0].alpha_2}'
            guide.save()


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0072_auto_20191212_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryguidepage',
            name='help_market_guide_cta_link',
        ),
        migrations.AddField(
            model_name='countryguidepage',
            name='duties_and_custom_procedures_cta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Check duties and customs procedures for exporting goods'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='madb_content',
            field=core.model_fields.MarkdownField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.RunPython(set_duties_and_custom_procedures_cta_link, reverse_code=migrations.RunPython.noop)
    ]
