# Generated by Django 2.2.10 on 2020-05-18 12:53

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_readiness', '0074_auto_20200518_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_description_row_two',
            field=core.model_fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_number_row_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_period_row_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='performancedashboardpage',
            name='data_title_row_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
