# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderation',
            new_name='ModerationRequest',
        ),
        migrations.RenameField(
            model_name='moderatorreview',
            old_name='moderation',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='moderatorreview',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.ModerationRequest', verbose_name='request'),
        ),
    ]
