# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_moderation_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeratorReview',
            new_name='ModerationResponse',
        ),
        migrations.AlterField(
            model_name='moderationresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='review.ModerationRequest', verbose_name='request'),
        ),
    ]
