# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('review', '0005_moderation_response_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('first_accessed_at', models.DateTimeField(null=True)),
                ('last_accessed_at', models.DateTimeField(null=True)),
                ('page_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='wagtailcore.PageRevision')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='review.Reviewer')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
