# Generated by Django 2.2.2 on 2019-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_moderationrequest_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
