# Generated by Django 2.2.2 on 2019-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_moderationrequest_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationrequest',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
