# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0005_auto_20180217_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_de',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_en_gb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_ja',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_pt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_pt_br',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='seo_description_zh_hans',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
