# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0009_auto_20180307_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_ar',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_de',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_en_gb',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_es',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_fr',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_ja',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_pt',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_pt_br',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_ru',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_one_icon_zh_hans',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_ar',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_de',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_en_gb',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_es',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_fr',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_ja',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_pt',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_pt_br',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_ru',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_three_icon_zh_hans',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_ar',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_de',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_en_gb',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_es',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_fr',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_ja',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_pt',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_pt_br',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_ru',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='lede_column_two_icon_zh_hans',
            field=models.CharField(blank=True, choices=[('https://directory-cms-test.s3.amazonaws.com/core/icons/infrastructure.png', 'Infrastructure'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/innovation.png', 'Innovation'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/investment.png', 'Investment'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/quality.png', 'Quality'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/research.png', 'Research'), ('https://directory-cms-test.s3.amazonaws.com/core/icons/skills.png', 'Skills')], max_length=255, null=True),
        ),
    ]
