# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('find_a_supplier', '0011_auto_20180309_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
                ('body_en_gb', wagtail.core.fields.RichTextField(null=True)),
                ('body_de', wagtail.core.fields.RichTextField(null=True)),
                ('body_ja', wagtail.core.fields.RichTextField(null=True)),
                ('body_ru', wagtail.core.fields.RichTextField(null=True)),
                ('body_zh_hans', wagtail.core.fields.RichTextField(null=True)),
                ('body_fr', wagtail.core.fields.RichTextField(null=True)),
                ('body_es', wagtail.core.fields.RichTextField(null=True)),
                ('body_pt', wagtail.core.fields.RichTextField(null=True)),
                ('body_pt_br', wagtail.core.fields.RichTextField(null=True)),
                ('body_ar', wagtail.core.fields.RichTextField(null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_name_en_gb', models.CharField(max_length=255, null=True)),
                ('author_name_de', models.CharField(max_length=255, null=True)),
                ('author_name_ja', models.CharField(max_length=255, null=True)),
                ('author_name_ru', models.CharField(max_length=255, null=True)),
                ('author_name_zh_hans', models.CharField(max_length=255, null=True)),
                ('author_name_fr', models.CharField(max_length=255, null=True)),
                ('author_name_es', models.CharField(max_length=255, null=True)),
                ('author_name_pt', models.CharField(max_length=255, null=True)),
                ('author_name_pt_br', models.CharField(max_length=255, null=True)),
                ('author_name_ar', models.CharField(max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_title_en_gb', models.CharField(max_length=255, null=True)),
                ('job_title_de', models.CharField(max_length=255, null=True)),
                ('job_title_ja', models.CharField(max_length=255, null=True)),
                ('job_title_ru', models.CharField(max_length=255, null=True)),
                ('job_title_zh_hans', models.CharField(max_length=255, null=True)),
                ('job_title_fr', models.CharField(max_length=255, null=True)),
                ('job_title_es', models.CharField(max_length=255, null=True)),
                ('job_title_pt', models.CharField(max_length=255, null=True)),
                ('job_title_pt_br', models.CharField(max_length=255, null=True)),
                ('job_title_ar', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('date_en_gb', models.DateField(null=True)),
                ('date_de', models.DateField(null=True)),
                ('date_ja', models.DateField(null=True)),
                ('date_ru', models.DateField(null=True)),
                ('date_zh_hans', models.DateField(null=True)),
                ('date_fr', models.DateField(null=True)),
                ('date_es', models.DateField(null=True)),
                ('date_pt', models.DateField(null=True)),
                ('date_pt_br', models.DateField(null=True)),
                ('date_ar', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
