# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0013_auto_20180214_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='article_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='article_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='article_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='article_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='article_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='article_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='find_a_supplier.IndustryArticlePage'),
        ),
    ]
