# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 20:04
from __future__ import unicode_literals

from django.db import migrations


# this migration used to call sync_page_translation_fields, but that call
# has been moved outside of migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0016_industrylistpage'),
    ]

    operations = []
