# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0017_auto_20180214_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustryListPage',
            new_name='IndustryLandingPage',
        ),
    ]
