# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 16:37
from __future__ import unicode_literals

from django.db import migrations


rename_pairs =  [
    ('lede', 'introduction_text'),
    ('lede_column_one', 'introduction_column_one_text'),
    ('lede_column_two', 'introduction_column_two_text'),
    ('lede_column_three', 'introduction_column_three_text'),
    ('lede_column_one_icon', 'introduction_column_one_icon'),
    ('lede_column_two_icon', 'introduction_column_two_icon'),
    ('lede_column_three_icon', 'introduction_column_three_icon')
]


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0021_auto_20180326_1622'),
    ]

    operations = [
        migrations.RenameField('IndustryPage', old_name, new_name)
        for old_name, new_name in rename_pairs
    ]
