# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0023_auto_20180326_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryarticlepage',
            name='seo_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
