# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0025_auto_20180328_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_de',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_en_gb',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_es',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_ja',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_pt',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_pt_br',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='industryarticlepage',
            name='seo_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_de',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_es',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_ja',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_pt',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='industrylandingpage',
            name='seo_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_de',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_es',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_ja',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_pt',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='seo_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_de',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_en_gb',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_es',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_ja',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_pt',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_pt_br',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='seo_description_zh_hans',
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='introduction_title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_en_gb',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_ja',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_pt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_pt_br',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_title_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
