# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 13:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0027_auto_20180403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_ar',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_de',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_en_gb',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_es',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_fr',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_ja',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_pt',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_pt_br',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_ru',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='contact_success_message_text_zh_hans',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
    ]
