# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0032_auto_20180406_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_ar',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_de',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_es',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_fr',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_ja',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_pt',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_ru',
        ),
        migrations.RemoveField(
            model_name='industrycontactpage',
            name='breadcrumb_label_zh_hans',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_ar',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_de',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_es',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_fr',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_ja',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_pt',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_ru',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_label_zh_hans',
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='breadcrumbs_label_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
