# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0033_auto_20180406_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_en_gb',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_ja',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_pt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_pt_br',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='call_to_action_text_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_ar',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_de',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_en_gb',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_es',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_fr',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_ja',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_pt',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_pt_br',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_ru',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='proposition_text_zh_hans',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
