# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 07:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0036_auto_20180410_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypage',
            name='article_five',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='article_four',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='article_one',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='article_six',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='article_three',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='article_two',
        ),
    ]
