# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 14:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0038_auto_20180411_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_ar',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_de',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_en_gb',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_es',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_fr',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_ja',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_pt',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_pt_br',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_ru',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='page_zh_hans',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='find_a_supplier.IndustryPage'),
        ),
    ]
