# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0040_auto_20180416_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypage',
            name='sector_value',
        ),
    ]
