# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0042_auto_20180418_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_search_input_placeholder_text',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
