# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0042_auto_20180417_1549'),
        ('find_a_supplier', '0043_auto_20180418_0811'),
    ]

    operations = [
    ]
