# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0046_auto_20180419_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title',
            field=models.CharField(default='More industries', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='more_industries_title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
