# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0047_auto_20180420_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='hero_image_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_en_gb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_caption_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
