# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0049_auto_20180424_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
