# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0049_auto_20180424_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='industry_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagearticlesummary',
            name='industry_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
