# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0051_auto_20180501_1706'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
