# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0051_auto_20180425_0909'),
        ('find_a_supplier', '0050_industrypage_show_on_homep'),
    ]

    operations = [
    ]
