# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 11:11
from __future__ import unicode_literals

import html2text
from wagtail.core.models import Orderable
from wagtail.core.rich_text import expand_db_html
from wagtail.core.fields import RichTextField
from wagtailmarkdown.fields import MarkdownField

from django.db import migrations


def html_to_markdown(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    for base_class in [Page, Orderable]:
        for model_class in base_class.__subclasses__():
            if not hasattr(model_class, 'objects'):
                continue
            field_names = []
            for field in model_class._meta.get_fields():
                if (
                    isinstance(field, RichTextField) or
                    isinstance(field, MarkdownField)
                ):
                    field_names.append(field.name)
            for page in model_class.objects.all():
                for field_name in field_names:
                    html = expand_db_html(getattr(page, field_name))
                    markdown = html2text.html2text(html).strip()
                    setattr(page, field_name, markdown)
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0051_industrypage_show_on_homep'),
    ]

    operations = [
        migrations.RunPython(html_to_markdown, migrations.RunPython.noop)
    ]
