# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0052_merge_20180426_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_ar',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_de',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_es',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_fr',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_ja',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_pt',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_ru',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_one_icon_zh_hans',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_ar',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_de',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_es',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_fr',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_ja',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_pt',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_ru',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_three_icon_zh_hans',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_ar',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_de',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_en_gb',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_es',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_fr',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_ja',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_pt',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_pt_br',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_ru',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='introduction_column_two_icon_zh_hans',
        ),
    ]
