# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0053_industrypage_show_on_industries_showcase_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text',
            field=models.CharField(default='Back to home', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='back_to_home_link_text_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title',
            field=models.CharField(default='Share', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industryarticlepage',
            name='social_share_title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
