# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 13:02
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0053_merge_20180426_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ru',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='proposition_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_de',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_es',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_pt_br',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ru',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='landingpagearticlesummary',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
