# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0054_auto_20180426_1302'),
        ('find_a_supplier', '0053_auto_20180426_1412'),
    ]

    operations = [
    ]
