# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0055_merge_20180426_1443'),
        ('find_a_supplier', '0055_auto_20180426_1521'),
    ]

    operations = [
    ]
