# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 16:28
from __future__ import unicode_literals

import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0057_remove_industrycontactpage_industry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ar',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_de',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_en_gb',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_es',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_fr',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ja',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_pt',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_pt_br',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_ru',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='body_zh_hans',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ar',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_de',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_en_gb',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_es',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_fr',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ja',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_pt',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_pt_br',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_ru',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='introduction_text_zh_hans',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ar',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_de',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_en_gb',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_es',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_fr',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ja',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_pt',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_pt_br',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_ru',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='success_message_text_zh_hans',
            field=core.fields.MarkdownField(blank=True, null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='company_list_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='hero_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_one_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_three_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='introduction_column_two_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='industries_list_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='proposition_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_four_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_one_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_three_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_column_two_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_ar',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_de',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_en_gb',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_es',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_fr',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_ja',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_pt',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_pt_br',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_ru',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='services_list_text_zh_hans',
            field=core.fields.MarkdownField(null=True, validators=[core.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='landingpagearticlesummary',
            name='body',
            field=core.fields.MarkdownField(validators=[core.validators.slug_hyperlinks]),
        ),
    ]
