# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 10:35
from __future__ import unicode_literals

from django.db import migrations


def html_to_markdown(apps, schema_editor):
    IndustryArticlePage = apps.get_model(
        'find_a_supplier', 'IndustryArticlePage'
    )

    for page in IndustryArticlePage.objects.all():
        page.proposition_text_en_gb = (
            page.proposition_text_en_gb.replace('### ', '')
        )
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0057_auto_20180427_1518'),
    ]

    operations = [
        migrations.RunPython(html_to_markdown, migrations.RunPython.noop)
    ]
