# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('find_a_supplier', '0058_auto_20180521_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypagearticlesummary',
            name='video_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
        migrations.AddField(
            model_name='landingpagearticlesummary',
            name='video_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
