# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 14:30
from __future__ import unicode_literals

from directory_constants.constants import cms
from django.db import migrations


MODELS_CLASS_NAMES = (
    'IndustryLandingPage',
    'IndustryArticlePage',
    'LandingPage',
    'IndustryContactPage'
)


def add_service_to_pages(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    for class_name in MODELS_CLASS_NAMES:
        model_class = apps.get_model('find_a_supplier', class_name)
        for page in model_class.objects.all():
            Service.objects.get_or_create(
                name=cms.FIND_A_SUPPLIER,
                page=page
            )


def remove_service_from_page(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.filter(name=cms.FIND_A_SUPPLIER).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0061_auto_20180604_1344'),
        ('core', '0008_auI tto_20180809_1215')
    ]

    operations = [
        migrations.RunPython(
            add_service_to_pages,
            reverse_code=remove_service_from_page
        )
    ]
