# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('find_a_supplier', '0062_auto_20180817_1630'), ('find_a_supplier', '0063_auto_20180821_0810'), ('find_a_supplier', '0064_findasupplierapp_service_name'), ('find_a_supplier', '0065_auto_20180829_1027')]

    dependencies = [
        ('find_a_supplier', '0061_auto_20180604_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryarticlepage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrycontactpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrylandingpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='findasupplierapp',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], db_index=True, max_length=100, null=True),
        ),
    ]
