# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0062_auto_20180817_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryarticlepage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='service_name',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest')], null=True, db_index=True, max_length=100),
        ),
    ]
