# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_singular', models.CharField(help_text='e.g. Content writer', max_length=100, verbose_name='name (singular)')),
                ('permission_summary', models.TextField(blank=True, help_text='A simple summary of what belonging to the group allows a user to do. Used to help managers decide what groups users should belong to. For example: Can only create drafts.')),
                ('role_match_description', models.TextField(blank=True, help_text='A simple description to help non-technical users understand which group is most suitable for them based on their real-life role. For example: If your role requires you to produce content for your department and you are located in POST or in the UK, you should select this as your role.')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(0, 'Visible to anyone'), (1, 'Visible only to managers and superusers'), (2, 'Visible only to superusers')], db_index=True, default=2)),
                ('seniority_level', models.PositiveSmallIntegerField(choices=[(1, '1 (lowest)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (highest)')], default=5, help_text="Used to order groups in a more natural way. For example, a 'Content editors' group might have the lowest value, and so should be displayed first.")),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'group info',
                'verbose_name_plural': 'group info',
                'ordering': ('visibility', 'seniority_level', 'name_singular'),
            },
        ),
    ]
