# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 11:54
from __future__ import unicode_literals

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    GroupInfo = apps.get_model('groups', 'GroupInfo')
    for group in Group.objects.all():
        GroupInfo.objects.create(group=group, name_singular=group.name)


def migrate_backwards(apps, schema_editor):
    GroupInfo = apps.get_model('groups', 'GroupInfo')
    GroupInfo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards, elidable=True),
    ]
