# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_create_groupinfo_for_existing_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='is_team_leaders_group',
            field=models.BooleanField(default=False),
        ),
    ]
