# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20190417_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercomponent',
            name='banner_content_pt_br',
        ),
        migrations.RemoveField(
            model_name='bannercomponent',
            name='banner_content_ru',
        ),
        migrations.RemoveField(
            model_name='bannercomponent',
            name='banner_label_pt_br',
        ),
        migrations.RemoveField(
            model_name='bannercomponent',
            name='banner_label_ru',
        ),
    ]
