# Generated by Django 2.2.4 on 2019-08-23 10:36

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20190417_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content',
            field=core.model_fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_ar',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_de',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_en_gb',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_es',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_fr',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_ja',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_pt',
            field=core.model_fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_zh_hans',
            field=core.model_fields.MarkdownField(null=True),
        ),
    ]
