# Generated by Django 4.1.9 on 2023-07-20 09:07

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ('components', '0005_auto_20190823_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_ar',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_de',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_en_gb',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_es',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_fr',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_ja',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_pt',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='bannercomponent',
            name='banner_content_zh_hans',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
    ]
