# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopage',
            name='view_app',
            field=models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness')], default='EXPORT_READINESS', help_text='The app the template will be rendered on', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demopage',
            name='view_path',
            field=models.CharField(default='', help_text='The path to view the rendered template', max_length=255),
            preserve_default=False,
        ),
    ]
