# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('moderation_queue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_at', models.DateTimeField(null=True)),
                ('business_approver', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.PageRevision', verbose_name='revision')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='accept page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='moderation_queue.Moderation', verbose_name='moderation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagependingmoderation',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='pagependingmoderation',
            name='user',
        ),
        migrations.DeleteModel(
            name='PagePendingModeration',
        ),
    ]
