# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_queue', '0002_rebuild_moderation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
