# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_queue', '0003_add_comment_to_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorreview',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
