# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_queue', '0004_moderatorreview_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderation',
            name='business_approver',
        ),
    ]
